-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity allo_DDitBlock_systolic_YV is
port (
    v8545_address0 : OUT STD_LOGIC_VECTOR (19 downto 0);
    v8545_ce0 : OUT STD_LOGIC;
    v8545_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    v8545_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    v8545_we0 : OUT STD_LOGIC;
    v8545_address1 : OUT STD_LOGIC_VECTOR (19 downto 0);
    v8545_ce1 : OUT STD_LOGIC;
    v8545_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    v8545_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    v8545_we1 : OUT STD_LOGIC;
    v8546_address0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    v8546_ce0 : OUT STD_LOGIC;
    v8546_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    v8546_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    v8546_we0 : OUT STD_LOGIC;
    v8546_address1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    v8546_ce1 : OUT STD_LOGIC;
    v8546_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    v8546_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    v8546_we1 : OUT STD_LOGIC;
    v8547_address0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    v8547_ce0 : OUT STD_LOGIC;
    v8547_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    v8547_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    v8547_we0 : OUT STD_LOGIC;
    v8547_address1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    v8547_ce1 : OUT STD_LOGIC;
    v8547_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    v8547_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    v8547_we1 : OUT STD_LOGIC;
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC );
end;


architecture behav of allo_DDitBlock_systolic_YV is 
    constant ap_const_lv20_0 : STD_LOGIC_VECTOR (19 downto 0) := "00000000000000000000";
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_lv8_80 : STD_LOGIC_VECTOR (7 downto 0) := "10000000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_boolean_1 : BOOLEAN := true;

attribute shreg_extract : string;
    signal dataflow_parent_loop_proc_U0_v8547_address0 : STD_LOGIC_VECTOR (15 downto 0);
    signal dataflow_parent_loop_proc_U0_v8547_ce0 : STD_LOGIC;
    signal dataflow_parent_loop_proc_U0_v8547_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal dataflow_parent_loop_proc_U0_v8547_we0 : STD_LOGIC;
    signal dataflow_parent_loop_proc_U0_v8547_address1 : STD_LOGIC_VECTOR (15 downto 0);
    signal dataflow_parent_loop_proc_U0_v8547_ce1 : STD_LOGIC;
    signal dataflow_parent_loop_proc_U0_v8547_d1 : STD_LOGIC_VECTOR (31 downto 0);
    signal dataflow_parent_loop_proc_U0_v8547_we1 : STD_LOGIC;
    signal dataflow_parent_loop_proc_U0_v8546_address0 : STD_LOGIC_VECTOR (15 downto 0);
    signal dataflow_parent_loop_proc_U0_v8546_ce0 : STD_LOGIC;
    signal dataflow_parent_loop_proc_U0_v8546_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal dataflow_parent_loop_proc_U0_v8546_we0 : STD_LOGIC;
    signal dataflow_parent_loop_proc_U0_v8546_address1 : STD_LOGIC_VECTOR (15 downto 0);
    signal dataflow_parent_loop_proc_U0_v8546_ce1 : STD_LOGIC;
    signal dataflow_parent_loop_proc_U0_v8546_d1 : STD_LOGIC_VECTOR (31 downto 0);
    signal dataflow_parent_loop_proc_U0_v8546_we1 : STD_LOGIC;
    signal dataflow_parent_loop_proc_U0_v8545_address0 : STD_LOGIC_VECTOR (19 downto 0);
    signal dataflow_parent_loop_proc_U0_v8545_ce0 : STD_LOGIC;
    signal dataflow_parent_loop_proc_U0_v8545_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal dataflow_parent_loop_proc_U0_v8545_we0 : STD_LOGIC;
    signal dataflow_parent_loop_proc_U0_v8545_address1 : STD_LOGIC_VECTOR (19 downto 0);
    signal dataflow_parent_loop_proc_U0_v8545_ce1 : STD_LOGIC;
    signal dataflow_parent_loop_proc_U0_v8545_d1 : STD_LOGIC_VECTOR (31 downto 0);
    signal dataflow_parent_loop_proc_U0_v8545_we1 : STD_LOGIC;
    signal dataflow_parent_loop_proc_U0_ap_start : STD_LOGIC;
    signal dataflow_parent_loop_proc_U0_ap_done : STD_LOGIC;
    signal dataflow_parent_loop_proc_U0_ap_ready : STD_LOGIC;
    signal dataflow_parent_loop_proc_U0_ap_idle : STD_LOGIC;
    signal dataflow_parent_loop_proc_U0_ap_continue : STD_LOGIC;
    signal loop_dataflow_input_count : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal loop_dataflow_output_count : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal bound_minus_1 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component allo_DDitBlock_dataflow_parent_loop_proc IS
    port (
        mi5 : IN STD_LOGIC_VECTOR (7 downto 0);
        v8547_address0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        v8547_ce0 : OUT STD_LOGIC;
        v8547_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        v8547_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        v8547_we0 : OUT STD_LOGIC;
        v8547_address1 : OUT STD_LOGIC_VECTOR (15 downto 0);
        v8547_ce1 : OUT STD_LOGIC;
        v8547_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        v8547_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        v8547_we1 : OUT STD_LOGIC;
        v8546_address0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        v8546_ce0 : OUT STD_LOGIC;
        v8546_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        v8546_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        v8546_we0 : OUT STD_LOGIC;
        v8546_address1 : OUT STD_LOGIC_VECTOR (15 downto 0);
        v8546_ce1 : OUT STD_LOGIC;
        v8546_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        v8546_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        v8546_we1 : OUT STD_LOGIC;
        v8545_address0 : OUT STD_LOGIC_VECTOR (19 downto 0);
        v8545_ce0 : OUT STD_LOGIC;
        v8545_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        v8545_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        v8545_we0 : OUT STD_LOGIC;
        v8545_address1 : OUT STD_LOGIC_VECTOR (19 downto 0);
        v8545_ce1 : OUT STD_LOGIC;
        v8545_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        v8545_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        v8545_we1 : OUT STD_LOGIC;
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        mi5_ap_vld : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC );
    end component;



begin
    dataflow_parent_loop_proc_U0 : component allo_DDitBlock_dataflow_parent_loop_proc
    port map (
        mi5 => loop_dataflow_input_count,
        v8547_address0 => dataflow_parent_loop_proc_U0_v8547_address0,
        v8547_ce0 => dataflow_parent_loop_proc_U0_v8547_ce0,
        v8547_d0 => dataflow_parent_loop_proc_U0_v8547_d0,
        v8547_q0 => ap_const_lv32_0,
        v8547_we0 => dataflow_parent_loop_proc_U0_v8547_we0,
        v8547_address1 => dataflow_parent_loop_proc_U0_v8547_address1,
        v8547_ce1 => dataflow_parent_loop_proc_U0_v8547_ce1,
        v8547_d1 => dataflow_parent_loop_proc_U0_v8547_d1,
        v8547_q1 => ap_const_lv32_0,
        v8547_we1 => dataflow_parent_loop_proc_U0_v8547_we1,
        v8546_address0 => dataflow_parent_loop_proc_U0_v8546_address0,
        v8546_ce0 => dataflow_parent_loop_proc_U0_v8546_ce0,
        v8546_d0 => dataflow_parent_loop_proc_U0_v8546_d0,
        v8546_q0 => v8546_q0,
        v8546_we0 => dataflow_parent_loop_proc_U0_v8546_we0,
        v8546_address1 => dataflow_parent_loop_proc_U0_v8546_address1,
        v8546_ce1 => dataflow_parent_loop_proc_U0_v8546_ce1,
        v8546_d1 => dataflow_parent_loop_proc_U0_v8546_d1,
        v8546_q1 => ap_const_lv32_0,
        v8546_we1 => dataflow_parent_loop_proc_U0_v8546_we1,
        v8545_address0 => dataflow_parent_loop_proc_U0_v8545_address0,
        v8545_ce0 => dataflow_parent_loop_proc_U0_v8545_ce0,
        v8545_d0 => dataflow_parent_loop_proc_U0_v8545_d0,
        v8545_q0 => v8545_q0,
        v8545_we0 => dataflow_parent_loop_proc_U0_v8545_we0,
        v8545_address1 => dataflow_parent_loop_proc_U0_v8545_address1,
        v8545_ce1 => dataflow_parent_loop_proc_U0_v8545_ce1,
        v8545_d1 => dataflow_parent_loop_proc_U0_v8545_d1,
        v8545_q1 => ap_const_lv32_0,
        v8545_we1 => dataflow_parent_loop_proc_U0_v8545_we1,
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        mi5_ap_vld => ap_const_logic_0,
        ap_start => dataflow_parent_loop_proc_U0_ap_start,
        ap_done => dataflow_parent_loop_proc_U0_ap_done,
        ap_ready => dataflow_parent_loop_proc_U0_ap_ready,
        ap_idle => dataflow_parent_loop_proc_U0_ap_idle,
        ap_continue => dataflow_parent_loop_proc_U0_ap_continue);





    loop_dataflow_input_count_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                loop_dataflow_input_count <= ap_const_lv8_0;
            else
                if ((not((loop_dataflow_input_count = bound_minus_1)) and (ap_start = ap_const_logic_1) and (dataflow_parent_loop_proc_U0_ap_ready = ap_const_logic_1))) then 
                    loop_dataflow_input_count <= std_logic_vector(unsigned(loop_dataflow_input_count) + unsigned(ap_const_lv8_1));
                elsif (((loop_dataflow_input_count = bound_minus_1) and (ap_start = ap_const_logic_1) and (dataflow_parent_loop_proc_U0_ap_ready = ap_const_logic_1))) then 
                    loop_dataflow_input_count <= ap_const_lv8_0;
                end if; 
            end if;
        end if;
    end process;


    loop_dataflow_output_count_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                loop_dataflow_output_count <= ap_const_lv8_0;
            else
                if ((not((loop_dataflow_output_count = bound_minus_1)) and (dataflow_parent_loop_proc_U0_ap_continue = ap_const_logic_1) and (dataflow_parent_loop_proc_U0_ap_done = ap_const_logic_1))) then 
                    loop_dataflow_output_count <= std_logic_vector(unsigned(loop_dataflow_output_count) + unsigned(ap_const_lv8_1));
                elsif (((loop_dataflow_output_count = bound_minus_1) and (dataflow_parent_loop_proc_U0_ap_continue = ap_const_logic_1) and (dataflow_parent_loop_proc_U0_ap_done = ap_const_logic_1))) then 
                    loop_dataflow_output_count <= ap_const_lv8_0;
                end if; 
            end if;
        end if;
    end process;


    ap_done_assign_proc : process(dataflow_parent_loop_proc_U0_ap_done, loop_dataflow_output_count, bound_minus_1)
    begin
        if (((loop_dataflow_output_count = bound_minus_1) and (dataflow_parent_loop_proc_U0_ap_done = ap_const_logic_1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(dataflow_parent_loop_proc_U0_ap_idle, ap_start, loop_dataflow_output_count)
    begin
        if (((loop_dataflow_output_count = ap_const_lv8_0) and (ap_start = ap_const_logic_0) and (dataflow_parent_loop_proc_U0_ap_idle = ap_const_logic_1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(dataflow_parent_loop_proc_U0_ap_ready, ap_start, loop_dataflow_input_count, bound_minus_1)
    begin
        if (((loop_dataflow_input_count = bound_minus_1) and (ap_start = ap_const_logic_1) and (dataflow_parent_loop_proc_U0_ap_ready = ap_const_logic_1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    bound_minus_1 <= std_logic_vector(unsigned(ap_const_lv8_80) - unsigned(ap_const_lv8_1));

    dataflow_parent_loop_proc_U0_ap_continue_assign_proc : process(ap_continue, loop_dataflow_output_count, bound_minus_1)
    begin
        if ((not((loop_dataflow_output_count = bound_minus_1)) or (ap_continue = ap_const_logic_1))) then 
            dataflow_parent_loop_proc_U0_ap_continue <= ap_const_logic_1;
        else 
            dataflow_parent_loop_proc_U0_ap_continue <= ap_const_logic_0;
        end if; 
    end process;

    dataflow_parent_loop_proc_U0_ap_start <= ap_start;
    v8545_address0 <= dataflow_parent_loop_proc_U0_v8545_address0;
    v8545_address1 <= ap_const_lv20_0;
    v8545_ce0 <= dataflow_parent_loop_proc_U0_v8545_ce0;
    v8545_ce1 <= ap_const_logic_0;
    v8545_d0 <= ap_const_lv32_0;
    v8545_d1 <= ap_const_lv32_0;
    v8545_we0 <= ap_const_logic_0;
    v8545_we1 <= ap_const_logic_0;
    v8546_address0 <= dataflow_parent_loop_proc_U0_v8546_address0;
    v8546_address1 <= ap_const_lv16_0;
    v8546_ce0 <= dataflow_parent_loop_proc_U0_v8546_ce0;
    v8546_ce1 <= ap_const_logic_0;
    v8546_d0 <= ap_const_lv32_0;
    v8546_d1 <= ap_const_lv32_0;
    v8546_we0 <= ap_const_logic_0;
    v8546_we1 <= ap_const_logic_0;
    v8547_address0 <= dataflow_parent_loop_proc_U0_v8547_address0;
    v8547_address1 <= ap_const_lv16_0;
    v8547_ce0 <= dataflow_parent_loop_proc_U0_v8547_ce0;
    v8547_ce1 <= ap_const_logic_0;
    v8547_d0 <= dataflow_parent_loop_proc_U0_v8547_d0;
    v8547_d1 <= ap_const_lv32_0;
    v8547_we0 <= dataflow_parent_loop_proc_U0_v8547_we0;
    v8547_we1 <= ap_const_logic_0;
end behav;
