// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module allo_DDitBlock_PE_kernel_Q_0_1_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        A_fifo1_1_0_dout,
        A_fifo1_1_0_num_data_valid,
        A_fifo1_1_0_fifo_cap,
        A_fifo1_1_0_empty_n,
        A_fifo1_1_0_read,
        B_fifo1_0_1_dout,
        B_fifo1_0_1_num_data_valid,
        B_fifo1_0_1_fifo_cap,
        B_fifo1_0_1_empty_n,
        B_fifo1_0_1_read,
        A_fifo1_1_1_din,
        A_fifo1_1_1_num_data_valid,
        A_fifo1_1_1_fifo_cap,
        A_fifo1_1_1_full_n,
        A_fifo1_1_1_write,
        B_fifo1_0_2_din,
        B_fifo1_0_2_num_data_valid,
        B_fifo1_0_2_fifo_cap,
        B_fifo1_0_2_full_n,
        B_fifo1_0_2_write,
        v486_1_0,
        v486_1_0_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 2'd1;
parameter    ap_ST_fsm_pp0_stage1 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [31:0] A_fifo1_1_0_dout;
input  [4:0] A_fifo1_1_0_num_data_valid;
input  [4:0] A_fifo1_1_0_fifo_cap;
input   A_fifo1_1_0_empty_n;
output   A_fifo1_1_0_read;
input  [31:0] B_fifo1_0_1_dout;
input  [4:0] B_fifo1_0_1_num_data_valid;
input  [4:0] B_fifo1_0_1_fifo_cap;
input   B_fifo1_0_1_empty_n;
output   B_fifo1_0_1_read;
output  [31:0] A_fifo1_1_1_din;
input  [4:0] A_fifo1_1_1_num_data_valid;
input  [4:0] A_fifo1_1_1_fifo_cap;
input   A_fifo1_1_1_full_n;
output   A_fifo1_1_1_write;
output  [31:0] B_fifo1_0_2_din;
input  [4:0] B_fifo1_0_2_num_data_valid;
input  [4:0] B_fifo1_0_2_fifo_cap;
input   B_fifo1_0_2_full_n;
output   B_fifo1_0_2_write;
output  [31:0] v486_1_0;
output   v486_1_0_ap_vld;

reg ap_idle;
reg A_fifo1_1_0_read;
reg B_fifo1_0_1_read;
reg A_fifo1_1_1_write;
reg B_fifo1_0_2_write;
reg[31:0] v486_1_0;
reg v486_1_0_ap_vld;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage1;
reg   [0:0] icmp_ln1028_reg_164;
reg    ap_block_state2_pp0_stage1_iter0;
reg    ap_block_pp0_stage1_subdone;
reg    ap_condition_exit_pp0_iter0_stage1;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    A_fifo1_1_0_blk_n;
wire    ap_block_pp0_stage1;
reg    B_fifo1_0_1_blk_n;
reg    A_fifo1_1_1_blk_n;
reg    B_fifo1_0_2_blk_n;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln1028_fu_110_p2;
reg   [0:0] icmp_ln1028_reg_164_pp0_iter1_reg;
wire   [9:0] k18_2_fu_116_p2;
reg   [9:0] k18_2_reg_168;
reg    ap_block_pp0_stage1_11001;
wire   [31:0] grp_fu_93_p2;
reg   [31:0] v497_reg_183;
reg    ap_enable_reg_pp0_iter0_reg;
reg   [31:0] v498_fu_46;
wire   [31:0] grp_fu_89_p2;
reg   [31:0] ap_sig_allocacmp_v498_load_1;
reg   [31:0] ap_sig_allocacmp_v498_load;
wire    ap_loop_init;
reg    ap_loop_init_pp0_iter1_reg;
reg   [9:0] k18_fu_50;
reg   [9:0] ap_sig_allocacmp_k18_1;
wire    ap_block_pp0_stage0;
reg    ap_block_pp0_stage1_01001;
reg   [31:0] v486_1_0_preg;
wire   [31:0] grp_fu_93_p0;
wire   [31:0] grp_fu_93_p1;
reg    grp_fu_89_ce;
reg    grp_fu_93_ce;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [1:0] ap_NS_fsm;
reg    ap_block_pp0_stage0_subdone;
reg    ap_idle_pp0_1to2;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_257;
reg    ap_condition_260;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 v498_fu_46 = 32'd0;
#0 k18_fu_50 = 10'd0;
#0 v486_1_0_preg = 32'd0;
end

allo_DDitBlock_fadd_32ns_32ns_32_3_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_3_full_dsp_1_U359(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(ap_sig_allocacmp_v498_load_1),
    .din1(v497_reg_183),
    .ce(grp_fu_89_ce),
    .dout(grp_fu_89_p2)
);

allo_DDitBlock_fmul_32ns_32ns_32_2_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_2_max_dsp_1_U360(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_93_p0),
    .din1(grp_fu_93_p1),
    .ce(grp_fu_93_ce),
    .dout(grp_fu_93_p2)
);

allo_DDitBlock_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage1),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(ap_continue)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage1_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage1)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        v486_1_0_preg <= 32'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_01001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln1028_reg_164_pp0_iter1_reg == 1'd1))) begin
            v486_1_0_preg <= ap_sig_allocacmp_v498_load;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if ((1'b1 == ap_condition_260)) begin
            k18_fu_50 <= 10'd0;
        end else if ((1'b1 == ap_condition_257)) begin
            k18_fu_50 <= k18_2_reg_168;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        if (((ap_enable_reg_pp0_iter1 == 1'b1) & (ap_loop_init_pp0_iter1_reg == 1'b1))) begin
            v498_fu_46 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            v498_fu_46 <= grp_fu_89_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_init_pp0_iter1_reg <= ap_loop_init;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln1028_reg_164 <= icmp_ln1028_fu_110_p2;
        icmp_ln1028_reg_164_pp0_iter1_reg <= icmp_ln1028_reg_164;
        k18_2_reg_168 <= k18_2_fu_116_p2;
        v497_reg_183 <= grp_fu_93_p2;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (icmp_ln1028_reg_164 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        A_fifo1_1_0_blk_n = A_fifo1_1_0_empty_n;
    end else begin
        A_fifo1_1_0_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln1028_reg_164 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        A_fifo1_1_0_read = 1'b1;
    end else begin
        A_fifo1_1_0_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (icmp_ln1028_reg_164 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        A_fifo1_1_1_blk_n = A_fifo1_1_1_full_n;
    end else begin
        A_fifo1_1_1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln1028_reg_164 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        A_fifo1_1_1_write = 1'b1;
    end else begin
        A_fifo1_1_1_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (icmp_ln1028_reg_164 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        B_fifo1_0_1_blk_n = B_fifo1_0_1_empty_n;
    end else begin
        B_fifo1_0_1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln1028_reg_164 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        B_fifo1_0_1_read = 1'b1;
    end else begin
        B_fifo1_0_1_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (icmp_ln1028_reg_164 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        B_fifo1_0_2_blk_n = B_fifo1_0_2_full_n;
    end else begin
        B_fifo1_0_2_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln1028_reg_164 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        B_fifo1_0_2_write = 1'b1;
    end else begin
        B_fifo1_0_2_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_subdone) & (icmp_ln1028_reg_164 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_1to2 = 1'b1;
    end else begin
        ap_idle_pp0_1to2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_k18_1 = 10'd0;
    end else begin
        ap_sig_allocacmp_k18_1 = k18_fu_50;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        if (((ap_enable_reg_pp0_iter1 == 1'b1) & (ap_loop_init_pp0_iter1_reg == 1'b1))) begin
            ap_sig_allocacmp_v498_load = 32'd0;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            ap_sig_allocacmp_v498_load = grp_fu_89_p2;
        end else begin
            ap_sig_allocacmp_v498_load = v498_fu_46;
        end
    end else begin
        ap_sig_allocacmp_v498_load = v498_fu_46;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        if (((ap_enable_reg_pp0_iter1 == 1'b1) & (ap_loop_init_pp0_iter1_reg == 1'b1))) begin
            ap_sig_allocacmp_v498_load_1 = 32'd0;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            ap_sig_allocacmp_v498_load_1 = grp_fu_89_p2;
        end else begin
            ap_sig_allocacmp_v498_load_1 = v498_fu_46;
        end
    end else begin
        ap_sig_allocacmp_v498_load_1 = v498_fu_46;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        grp_fu_89_ce = 1'b1;
    end else begin
        grp_fu_89_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        grp_fu_93_ce = 1'b1;
    end else begin
        grp_fu_93_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_01001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln1028_reg_164_pp0_iter1_reg == 1'd1))) begin
        v486_1_0 = ap_sig_allocacmp_v498_load;
    end else begin
        v486_1_0 = v486_1_0_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln1028_reg_164_pp0_iter1_reg == 1'd1))) begin
        v486_1_0_ap_vld = 1'b1;
    end else begin
        v486_1_0_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to2 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign A_fifo1_1_1_din = A_fifo1_1_0_dout;

assign B_fifo1_0_2_din = B_fifo1_0_1_dout;

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_01001 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage1_iter0));
end

always @ (*) begin
    ap_block_pp0_stage1_11001 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage1_iter0));
end

always @ (*) begin
    ap_block_pp0_stage1_subdone = ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage1_iter0));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_done_reg == 1'b1);
end

always @ (*) begin
    ap_block_state2_pp0_stage1_iter0 = (((icmp_ln1028_reg_164 == 1'd0) & (1'b0 == B_fifo1_0_2_full_n)) | ((icmp_ln1028_reg_164 == 1'd0) & (1'b0 == A_fifo1_1_1_full_n)) | ((icmp_ln1028_reg_164 == 1'd0) & (1'b0 == B_fifo1_0_1_empty_n)) | ((icmp_ln1028_reg_164 == 1'd0) & (1'b0 == A_fifo1_1_0_empty_n)));
end

always @ (*) begin
    ap_condition_257 = ((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln1028_reg_164 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1));
end

always @ (*) begin
    ap_condition_260 = ((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage1;

assign grp_fu_93_p0 = A_fifo1_1_0_dout;

assign grp_fu_93_p1 = B_fifo1_0_1_dout;

assign icmp_ln1028_fu_110_p2 = ((ap_sig_allocacmp_k18_1 == 10'd512) ? 1'b1 : 1'b0);

assign k18_2_fu_116_p2 = (ap_sig_allocacmp_k18_1 + 10'd1);

endmodule //allo_DDitBlock_PE_kernel_Q_0_1_1
