// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module allo_DDitBlock_dataflow_in_loop_l_ni5_Loop_l_load_A_tile_ak5_proc5230_Pipeline_l_load_A_tile_ak (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        local_A5_7_i_address0,
        local_A5_7_i_ce0,
        local_A5_7_i_we0,
        local_A5_7_i_d0,
        local_A5_6_i_address0,
        local_A5_6_i_ce0,
        local_A5_6_i_we0,
        local_A5_6_i_d0,
        local_A5_5_i_address0,
        local_A5_5_i_ce0,
        local_A5_5_i_we0,
        local_A5_5_i_d0,
        local_A5_4_i_address0,
        local_A5_4_i_ce0,
        local_A5_4_i_we0,
        local_A5_4_i_d0,
        local_A5_3_i_address0,
        local_A5_3_i_ce0,
        local_A5_3_i_we0,
        local_A5_3_i_d0,
        local_A5_2_i_address0,
        local_A5_2_i_ce0,
        local_A5_2_i_we0,
        local_A5_2_i_d0,
        local_A5_1_i_address0,
        local_A5_1_i_ce0,
        local_A5_1_i_we0,
        local_A5_1_i_d0,
        local_A5_i_address0,
        local_A5_i_ce0,
        local_A5_i_we0,
        local_A5_i_d0,
        v8556_i,
        tmp_i,
        v8545_address0,
        v8545_ce0,
        v8545_q0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [9:0] local_A5_7_i_address0;
output   local_A5_7_i_ce0;
output   local_A5_7_i_we0;
output  [31:0] local_A5_7_i_d0;
output  [9:0] local_A5_6_i_address0;
output   local_A5_6_i_ce0;
output   local_A5_6_i_we0;
output  [31:0] local_A5_6_i_d0;
output  [9:0] local_A5_5_i_address0;
output   local_A5_5_i_ce0;
output   local_A5_5_i_we0;
output  [31:0] local_A5_5_i_d0;
output  [9:0] local_A5_4_i_address0;
output   local_A5_4_i_ce0;
output   local_A5_4_i_we0;
output  [31:0] local_A5_4_i_d0;
output  [9:0] local_A5_3_i_address0;
output   local_A5_3_i_ce0;
output   local_A5_3_i_we0;
output  [31:0] local_A5_3_i_d0;
output  [9:0] local_A5_2_i_address0;
output   local_A5_2_i_ce0;
output   local_A5_2_i_we0;
output  [31:0] local_A5_2_i_d0;
output  [9:0] local_A5_1_i_address0;
output   local_A5_1_i_ce0;
output   local_A5_1_i_we0;
output  [31:0] local_A5_1_i_d0;
output  [9:0] local_A5_i_address0;
output   local_A5_i_ce0;
output   local_A5_i_we0;
output  [31:0] local_A5_i_d0;
input  [0:0] v8556_i;
input  [9:0] tmp_i;
output  [19:0] v8545_address0;
output   v8545_ce0;
input  [31:0] v8545_q0;

reg ap_idle;
reg local_A5_7_i_ce0;
reg local_A5_7_i_we0;
reg local_A5_6_i_ce0;
reg local_A5_6_i_we0;
reg local_A5_5_i_ce0;
reg local_A5_5_i_we0;
reg local_A5_4_i_ce0;
reg local_A5_4_i_we0;
reg local_A5_3_i_ce0;
reg local_A5_3_i_we0;
reg local_A5_2_i_ce0;
reg local_A5_2_i_we0;
reg local_A5_1_i_ce0;
reg local_A5_1_i_we0;
reg local_A5_i_ce0;
reg local_A5_i_we0;
reg v8545_ce0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln15537_fu_253_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [0:0] v8556_i_read_reg_389;
wire    ap_block_pp0_stage0_11001;
wire   [10:0] select_ln15537_1_fu_291_p3;
reg   [10:0] select_ln15537_1_reg_396;
wire   [2:0] trunc_ln15541_fu_307_p1;
reg   [2:0] trunc_ln15541_reg_401;
wire   [63:0] zext_ln15543_fu_331_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln15537_fu_357_p1;
reg   [3:0] ai5_fu_86;
wire   [3:0] add_ln15538_fu_336_p2;
wire    ap_loop_init;
reg   [3:0] ap_sig_allocacmp_ai5_load;
reg   [10:0] ak5_fu_90;
reg   [10:0] ap_sig_allocacmp_ak5_load;
reg   [13:0] indvar_flatten_i_fu_94;
wire   [13:0] add_ln15537_fu_259_p2;
reg   [13:0] ap_sig_allocacmp_indvar_flatten_i_load;
wire   [0:0] icmp_ln15538_fu_277_p2;
wire   [10:0] add_ln15537_1_fu_271_p2;
wire   [3:0] select_ln15537_fu_283_p3;
wire   [9:0] zext_ln15538_fu_303_p1;
wire   [9:0] add_ln15543_fu_311_p2;
wire   [19:0] tmp_55_i_fu_317_p3;
wire   [19:0] select_ln15537_1_i_cast_fu_299_p1;
wire   [19:0] add_ln15543_1_fu_325_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ai5_fu_86 = 4'd0;
#0 ak5_fu_90 = 11'd0;
#0 indvar_flatten_i_fu_94 = 14'd0;
#0 ap_done_reg = 1'b0;
end

allo_DDitBlock_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln15537_fu_253_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            ai5_fu_86 <= add_ln15538_fu_336_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            ai5_fu_86 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln15537_fu_253_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            ak5_fu_90 <= select_ln15537_1_fu_291_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            ak5_fu_90 <= 11'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln15537_fu_253_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten_i_fu_94 <= add_ln15537_fu_259_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_i_fu_94 <= 14'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        select_ln15537_1_reg_396 <= select_ln15537_1_fu_291_p3;
        trunc_ln15541_reg_401 <= trunc_ln15541_fu_307_p1;
    end
end

always @ (*) begin
    if (((icmp_ln15537_fu_253_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_ai5_load = 4'd0;
    end else begin
        ap_sig_allocacmp_ai5_load = ai5_fu_86;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_ak5_load = 11'd0;
    end else begin
        ap_sig_allocacmp_ak5_load = ak5_fu_90;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten_i_load = 14'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_i_load = indvar_flatten_i_fu_94;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_A5_1_i_ce0 = 1'b1;
    end else begin
        local_A5_1_i_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln15541_reg_401 == 3'd6) & (v8556_i_read_reg_389 == 1'd1))) begin
        local_A5_1_i_we0 = 1'b1;
    end else begin
        local_A5_1_i_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_A5_2_i_ce0 = 1'b1;
    end else begin
        local_A5_2_i_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln15541_reg_401 == 3'd5) & (v8556_i_read_reg_389 == 1'd1))) begin
        local_A5_2_i_we0 = 1'b1;
    end else begin
        local_A5_2_i_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_A5_3_i_ce0 = 1'b1;
    end else begin
        local_A5_3_i_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln15541_reg_401 == 3'd4) & (v8556_i_read_reg_389 == 1'd1))) begin
        local_A5_3_i_we0 = 1'b1;
    end else begin
        local_A5_3_i_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_A5_4_i_ce0 = 1'b1;
    end else begin
        local_A5_4_i_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln15541_reg_401 == 3'd3) & (v8556_i_read_reg_389 == 1'd1))) begin
        local_A5_4_i_we0 = 1'b1;
    end else begin
        local_A5_4_i_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_A5_5_i_ce0 = 1'b1;
    end else begin
        local_A5_5_i_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln15541_reg_401 == 3'd2) & (v8556_i_read_reg_389 == 1'd1))) begin
        local_A5_5_i_we0 = 1'b1;
    end else begin
        local_A5_5_i_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_A5_6_i_ce0 = 1'b1;
    end else begin
        local_A5_6_i_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln15541_reg_401 == 3'd1) & (v8556_i_read_reg_389 == 1'd1))) begin
        local_A5_6_i_we0 = 1'b1;
    end else begin
        local_A5_6_i_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_A5_7_i_ce0 = 1'b1;
    end else begin
        local_A5_7_i_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln15541_reg_401 == 3'd0) & (v8556_i_read_reg_389 == 1'd1))) begin
        local_A5_7_i_we0 = 1'b1;
    end else begin
        local_A5_7_i_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_A5_i_ce0 = 1'b1;
    end else begin
        local_A5_i_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln15541_reg_401 == 3'd7) & (v8556_i_read_reg_389 == 1'd1))) begin
        local_A5_i_we0 = 1'b1;
    end else begin
        local_A5_i_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        v8545_ce0 = 1'b1;
    end else begin
        v8545_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln15537_1_fu_271_p2 = (ap_sig_allocacmp_ak5_load + 11'd1);

assign add_ln15537_fu_259_p2 = (ap_sig_allocacmp_indvar_flatten_i_load + 14'd1);

assign add_ln15538_fu_336_p2 = (select_ln15537_fu_283_p3 + 4'd1);

assign add_ln15543_1_fu_325_p2 = (tmp_55_i_fu_317_p3 + select_ln15537_1_i_cast_fu_299_p1);

assign add_ln15543_fu_311_p2 = (tmp_i + zext_ln15538_fu_303_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign icmp_ln15537_fu_253_p2 = ((ap_sig_allocacmp_indvar_flatten_i_load == 14'd8192) ? 1'b1 : 1'b0);

assign icmp_ln15538_fu_277_p2 = ((ap_sig_allocacmp_ai5_load == 4'd8) ? 1'b1 : 1'b0);

assign local_A5_1_i_address0 = zext_ln15537_fu_357_p1;

assign local_A5_1_i_d0 = v8545_q0;

assign local_A5_2_i_address0 = zext_ln15537_fu_357_p1;

assign local_A5_2_i_d0 = v8545_q0;

assign local_A5_3_i_address0 = zext_ln15537_fu_357_p1;

assign local_A5_3_i_d0 = v8545_q0;

assign local_A5_4_i_address0 = zext_ln15537_fu_357_p1;

assign local_A5_4_i_d0 = v8545_q0;

assign local_A5_5_i_address0 = zext_ln15537_fu_357_p1;

assign local_A5_5_i_d0 = v8545_q0;

assign local_A5_6_i_address0 = zext_ln15537_fu_357_p1;

assign local_A5_6_i_d0 = v8545_q0;

assign local_A5_7_i_address0 = zext_ln15537_fu_357_p1;

assign local_A5_7_i_d0 = v8545_q0;

assign local_A5_i_address0 = zext_ln15537_fu_357_p1;

assign local_A5_i_d0 = v8545_q0;

assign select_ln15537_1_fu_291_p3 = ((icmp_ln15538_fu_277_p2[0:0] == 1'b1) ? add_ln15537_1_fu_271_p2 : ap_sig_allocacmp_ak5_load);

assign select_ln15537_1_i_cast_fu_299_p1 = select_ln15537_1_fu_291_p3;

assign select_ln15537_fu_283_p3 = ((icmp_ln15538_fu_277_p2[0:0] == 1'b1) ? 4'd0 : ap_sig_allocacmp_ai5_load);

assign tmp_55_i_fu_317_p3 = {{add_ln15543_fu_311_p2}, {10'd0}};

assign trunc_ln15541_fu_307_p1 = select_ln15537_fu_283_p3[2:0];

assign v8545_address0 = zext_ln15543_fu_331_p1;

assign v8556_i_read_reg_389 = v8556_i;

assign zext_ln15537_fu_357_p1 = select_ln15537_1_reg_396;

assign zext_ln15538_fu_303_p1 = select_ln15537_fu_283_p3;

assign zext_ln15543_fu_331_p1 = add_ln15543_1_fu_325_p2;

endmodule //allo_DDitBlock_dataflow_in_loop_l_ni5_Loop_l_load_A_tile_ak5_proc5230_Pipeline_l_load_A_tile_ak
