-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity allo_DDitBlock_systolic_tile_QKT_Loop_l_data_load_k272_proc26 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    A_fifo4_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_fifo4_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
    A_fifo4_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
    A_fifo4_full_n : IN STD_LOGIC;
    A_fifo4_write : OUT STD_LOGIC;
    A_fifo4_9_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_fifo4_9_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
    A_fifo4_9_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
    A_fifo4_9_full_n : IN STD_LOGIC;
    A_fifo4_9_write : OUT STD_LOGIC;
    A_fifo4_18_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_fifo4_18_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
    A_fifo4_18_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
    A_fifo4_18_full_n : IN STD_LOGIC;
    A_fifo4_18_write : OUT STD_LOGIC;
    A_fifo4_27_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_fifo4_27_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
    A_fifo4_27_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
    A_fifo4_27_full_n : IN STD_LOGIC;
    A_fifo4_27_write : OUT STD_LOGIC;
    A_fifo4_36_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_fifo4_36_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
    A_fifo4_36_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
    A_fifo4_36_full_n : IN STD_LOGIC;
    A_fifo4_36_write : OUT STD_LOGIC;
    A_fifo4_45_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_fifo4_45_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
    A_fifo4_45_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
    A_fifo4_45_full_n : IN STD_LOGIC;
    A_fifo4_45_write : OUT STD_LOGIC;
    A_fifo4_54_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_fifo4_54_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
    A_fifo4_54_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
    A_fifo4_54_full_n : IN STD_LOGIC;
    A_fifo4_54_write : OUT STD_LOGIC;
    A_fifo4_63_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_fifo4_63_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
    A_fifo4_63_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
    A_fifo4_63_full_n : IN STD_LOGIC;
    A_fifo4_63_write : OUT STD_LOGIC;
    B_fifo4_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    B_fifo4_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
    B_fifo4_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
    B_fifo4_full_n : IN STD_LOGIC;
    B_fifo4_write : OUT STD_LOGIC;
    B_fifo4_9_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    B_fifo4_9_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
    B_fifo4_9_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
    B_fifo4_9_full_n : IN STD_LOGIC;
    B_fifo4_9_write : OUT STD_LOGIC;
    B_fifo4_18_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    B_fifo4_18_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
    B_fifo4_18_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
    B_fifo4_18_full_n : IN STD_LOGIC;
    B_fifo4_18_write : OUT STD_LOGIC;
    B_fifo4_27_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    B_fifo4_27_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
    B_fifo4_27_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
    B_fifo4_27_full_n : IN STD_LOGIC;
    B_fifo4_27_write : OUT STD_LOGIC;
    B_fifo4_36_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    B_fifo4_36_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
    B_fifo4_36_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
    B_fifo4_36_full_n : IN STD_LOGIC;
    B_fifo4_36_write : OUT STD_LOGIC;
    B_fifo4_45_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    B_fifo4_45_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
    B_fifo4_45_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
    B_fifo4_45_full_n : IN STD_LOGIC;
    B_fifo4_45_write : OUT STD_LOGIC;
    B_fifo4_54_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    B_fifo4_54_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
    B_fifo4_54_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
    B_fifo4_54_full_n : IN STD_LOGIC;
    B_fifo4_54_write : OUT STD_LOGIC;
    B_fifo4_63_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    B_fifo4_63_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
    B_fifo4_63_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
    B_fifo4_63_full_n : IN STD_LOGIC;
    B_fifo4_63_write : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    v6609_0_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    v6609_0_ce0 : OUT STD_LOGIC;
    v6609_0_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    v6609_1_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    v6609_1_ce0 : OUT STD_LOGIC;
    v6609_1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    v6609_2_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    v6609_2_ce0 : OUT STD_LOGIC;
    v6609_2_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    v6609_3_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    v6609_3_ce0 : OUT STD_LOGIC;
    v6609_3_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    v6609_4_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    v6609_4_ce0 : OUT STD_LOGIC;
    v6609_4_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    v6609_5_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    v6609_5_ce0 : OUT STD_LOGIC;
    v6609_5_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    v6609_6_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    v6609_6_ce0 : OUT STD_LOGIC;
    v6609_6_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    v6609_7_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    v6609_7_ce0 : OUT STD_LOGIC;
    v6609_7_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    v6610_0_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    v6610_0_ce0 : OUT STD_LOGIC;
    v6610_0_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    v6610_1_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    v6610_1_ce0 : OUT STD_LOGIC;
    v6610_1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    v6610_2_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    v6610_2_ce0 : OUT STD_LOGIC;
    v6610_2_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    v6610_3_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    v6610_3_ce0 : OUT STD_LOGIC;
    v6610_3_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    v6610_4_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    v6610_4_ce0 : OUT STD_LOGIC;
    v6610_4_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    v6610_5_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    v6610_5_ce0 : OUT STD_LOGIC;
    v6610_5_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    v6610_6_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    v6610_6_ce0 : OUT STD_LOGIC;
    v6610_6_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    v6610_7_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    v6610_7_ce0 : OUT STD_LOGIC;
    v6610_7_q0 : IN STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of allo_DDitBlock_systolic_tile_QKT_Loop_l_data_load_k272_proc26 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv7_40 : STD_LOGIC_VECTOR (6 downto 0) := "1000000";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal internal_ap_ready : STD_LOGIC;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln12247_fu_428_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal A_fifo4_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal A_fifo4_9_blk_n : STD_LOGIC;
    signal A_fifo4_18_blk_n : STD_LOGIC;
    signal A_fifo4_27_blk_n : STD_LOGIC;
    signal A_fifo4_36_blk_n : STD_LOGIC;
    signal A_fifo4_45_blk_n : STD_LOGIC;
    signal A_fifo4_54_blk_n : STD_LOGIC;
    signal A_fifo4_63_blk_n : STD_LOGIC;
    signal B_fifo4_blk_n : STD_LOGIC;
    signal B_fifo4_9_blk_n : STD_LOGIC;
    signal B_fifo4_18_blk_n : STD_LOGIC;
    signal B_fifo4_27_blk_n : STD_LOGIC;
    signal B_fifo4_36_blk_n : STD_LOGIC;
    signal B_fifo4_45_blk_n : STD_LOGIC;
    signal B_fifo4_54_blk_n : STD_LOGIC;
    signal B_fifo4_63_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal zext_ln12247_fu_440_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal k272_fu_96 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    signal add_ln12247_fu_434_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_k272_1 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_condition_363 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component allo_DDitBlock_flow_control_loop_pipe IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC;
        ap_continue : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_U : component allo_DDitBlock_flow_control_loop_pipe
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => real_start,
        ap_ready => internal_ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int,
        ap_continue => ap_continue);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((real_start = ap_const_logic_1) and (internal_ap_ready = ap_const_logic_0))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    k272_fu_96_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_363)) then
                if ((icmp_ln12247_fu_428_p2 = ap_const_lv1_0)) then 
                    k272_fu_96 <= add_ln12247_fu_434_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    k272_fu_96 <= ap_const_lv7_0;
                end if;
            end if; 
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;

    A_fifo4_18_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, A_fifo4_18_full_n, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            A_fifo4_18_blk_n <= A_fifo4_18_full_n;
        else 
            A_fifo4_18_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    A_fifo4_18_din <= v6609_2_q0;

    A_fifo4_18_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            A_fifo4_18_write <= ap_const_logic_1;
        else 
            A_fifo4_18_write <= ap_const_logic_0;
        end if; 
    end process;


    A_fifo4_27_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, A_fifo4_27_full_n, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            A_fifo4_27_blk_n <= A_fifo4_27_full_n;
        else 
            A_fifo4_27_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    A_fifo4_27_din <= v6609_3_q0;

    A_fifo4_27_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            A_fifo4_27_write <= ap_const_logic_1;
        else 
            A_fifo4_27_write <= ap_const_logic_0;
        end if; 
    end process;


    A_fifo4_36_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, A_fifo4_36_full_n, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            A_fifo4_36_blk_n <= A_fifo4_36_full_n;
        else 
            A_fifo4_36_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    A_fifo4_36_din <= v6609_4_q0;

    A_fifo4_36_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            A_fifo4_36_write <= ap_const_logic_1;
        else 
            A_fifo4_36_write <= ap_const_logic_0;
        end if; 
    end process;


    A_fifo4_45_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, A_fifo4_45_full_n, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            A_fifo4_45_blk_n <= A_fifo4_45_full_n;
        else 
            A_fifo4_45_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    A_fifo4_45_din <= v6609_5_q0;

    A_fifo4_45_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            A_fifo4_45_write <= ap_const_logic_1;
        else 
            A_fifo4_45_write <= ap_const_logic_0;
        end if; 
    end process;


    A_fifo4_54_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, A_fifo4_54_full_n, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            A_fifo4_54_blk_n <= A_fifo4_54_full_n;
        else 
            A_fifo4_54_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    A_fifo4_54_din <= v6609_6_q0;

    A_fifo4_54_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            A_fifo4_54_write <= ap_const_logic_1;
        else 
            A_fifo4_54_write <= ap_const_logic_0;
        end if; 
    end process;


    A_fifo4_63_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, A_fifo4_63_full_n, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            A_fifo4_63_blk_n <= A_fifo4_63_full_n;
        else 
            A_fifo4_63_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    A_fifo4_63_din <= v6609_7_q0;

    A_fifo4_63_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            A_fifo4_63_write <= ap_const_logic_1;
        else 
            A_fifo4_63_write <= ap_const_logic_0;
        end if; 
    end process;


    A_fifo4_9_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, A_fifo4_9_full_n, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            A_fifo4_9_blk_n <= A_fifo4_9_full_n;
        else 
            A_fifo4_9_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    A_fifo4_9_din <= v6609_1_q0;

    A_fifo4_9_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            A_fifo4_9_write <= ap_const_logic_1;
        else 
            A_fifo4_9_write <= ap_const_logic_0;
        end if; 
    end process;


    A_fifo4_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, A_fifo4_full_n, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            A_fifo4_blk_n <= A_fifo4_full_n;
        else 
            A_fifo4_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    A_fifo4_din <= v6609_0_q0;

    A_fifo4_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            A_fifo4_write <= ap_const_logic_1;
        else 
            A_fifo4_write <= ap_const_logic_0;
        end if; 
    end process;


    B_fifo4_18_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, B_fifo4_18_full_n, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            B_fifo4_18_blk_n <= B_fifo4_18_full_n;
        else 
            B_fifo4_18_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    B_fifo4_18_din <= v6610_2_q0;

    B_fifo4_18_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            B_fifo4_18_write <= ap_const_logic_1;
        else 
            B_fifo4_18_write <= ap_const_logic_0;
        end if; 
    end process;


    B_fifo4_27_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, B_fifo4_27_full_n, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            B_fifo4_27_blk_n <= B_fifo4_27_full_n;
        else 
            B_fifo4_27_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    B_fifo4_27_din <= v6610_3_q0;

    B_fifo4_27_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            B_fifo4_27_write <= ap_const_logic_1;
        else 
            B_fifo4_27_write <= ap_const_logic_0;
        end if; 
    end process;


    B_fifo4_36_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, B_fifo4_36_full_n, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            B_fifo4_36_blk_n <= B_fifo4_36_full_n;
        else 
            B_fifo4_36_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    B_fifo4_36_din <= v6610_4_q0;

    B_fifo4_36_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            B_fifo4_36_write <= ap_const_logic_1;
        else 
            B_fifo4_36_write <= ap_const_logic_0;
        end if; 
    end process;


    B_fifo4_45_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, B_fifo4_45_full_n, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            B_fifo4_45_blk_n <= B_fifo4_45_full_n;
        else 
            B_fifo4_45_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    B_fifo4_45_din <= v6610_5_q0;

    B_fifo4_45_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            B_fifo4_45_write <= ap_const_logic_1;
        else 
            B_fifo4_45_write <= ap_const_logic_0;
        end if; 
    end process;


    B_fifo4_54_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, B_fifo4_54_full_n, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            B_fifo4_54_blk_n <= B_fifo4_54_full_n;
        else 
            B_fifo4_54_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    B_fifo4_54_din <= v6610_6_q0;

    B_fifo4_54_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            B_fifo4_54_write <= ap_const_logic_1;
        else 
            B_fifo4_54_write <= ap_const_logic_0;
        end if; 
    end process;


    B_fifo4_63_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, B_fifo4_63_full_n, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            B_fifo4_63_blk_n <= B_fifo4_63_full_n;
        else 
            B_fifo4_63_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    B_fifo4_63_din <= v6610_7_q0;

    B_fifo4_63_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            B_fifo4_63_write <= ap_const_logic_1;
        else 
            B_fifo4_63_write <= ap_const_logic_0;
        end if; 
    end process;


    B_fifo4_9_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, B_fifo4_9_full_n, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            B_fifo4_9_blk_n <= B_fifo4_9_full_n;
        else 
            B_fifo4_9_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    B_fifo4_9_din <= v6610_1_q0;

    B_fifo4_9_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            B_fifo4_9_write <= ap_const_logic_1;
        else 
            B_fifo4_9_write <= ap_const_logic_0;
        end if; 
    end process;


    B_fifo4_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, B_fifo4_full_n, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            B_fifo4_blk_n <= B_fifo4_full_n;
        else 
            B_fifo4_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    B_fifo4_din <= v6610_0_q0;

    B_fifo4_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            B_fifo4_write <= ap_const_logic_1;
        else 
            B_fifo4_write <= ap_const_logic_0;
        end if; 
    end process;

    add_ln12247_fu_434_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_k272_1) + unsigned(ap_const_lv7_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_done_reg, ap_block_state1_pp0_stage0_iter0, ap_block_state2_pp0_stage0_iter1, ap_start_int)
    begin
                ap_block_pp0_stage0_01001 <= ((ap_done_reg = ap_const_logic_1) or ((ap_start_int = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_done_reg, ap_block_state1_pp0_stage0_iter0, ap_block_state2_pp0_stage0_iter1, ap_start_int)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_done_reg = ap_const_logic_1) or ((ap_start_int = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_done_reg, ap_block_state1_pp0_stage0_iter0, ap_block_state2_pp0_stage0_iter1, ap_start_int)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_done_reg = ap_const_logic_1) or ((ap_start_int = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1)));
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(ap_done_reg)
    begin
                ap_block_state1_pp0_stage0_iter0 <= (ap_done_reg = ap_const_logic_1);
    end process;


    ap_block_state2_pp0_stage0_iter1_assign_proc : process(A_fifo4_full_n, A_fifo4_9_full_n, A_fifo4_18_full_n, A_fifo4_27_full_n, A_fifo4_36_full_n, A_fifo4_45_full_n, A_fifo4_54_full_n, A_fifo4_63_full_n, B_fifo4_full_n, B_fifo4_9_full_n, B_fifo4_18_full_n, B_fifo4_27_full_n, B_fifo4_36_full_n, B_fifo4_45_full_n, B_fifo4_54_full_n, B_fifo4_63_full_n)
    begin
                ap_block_state2_pp0_stage0_iter1 <= ((ap_const_logic_0 = A_fifo4_54_full_n) or (ap_const_logic_0 = A_fifo4_45_full_n) or (ap_const_logic_0 = A_fifo4_36_full_n) or (ap_const_logic_0 = A_fifo4_27_full_n) or (ap_const_logic_0 = A_fifo4_18_full_n) or (ap_const_logic_0 = A_fifo4_9_full_n) or (ap_const_logic_0 = A_fifo4_full_n) or (ap_const_logic_0 = B_fifo4_63_full_n) or (ap_const_logic_0 = B_fifo4_54_full_n) or (ap_const_logic_0 = B_fifo4_45_full_n) or (ap_const_logic_0 = B_fifo4_36_full_n) or (ap_const_logic_0 = B_fifo4_27_full_n) or (ap_const_logic_0 = B_fifo4_18_full_n) or (ap_const_logic_0 = B_fifo4_9_full_n) or (ap_const_logic_0 = B_fifo4_full_n) or (ap_const_logic_0 = A_fifo4_63_full_n));
    end process;


    ap_condition_363_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
                ap_condition_363 <= ((ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, icmp_ln12247_fu_428_p2, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln12247_fu_428_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_done_reg, ap_block_pp0_stage0_subdone, ap_loop_exit_ready)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= internal_ap_ready;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_k272_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, k272_fu_96, ap_loop_init, ap_start_int)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_sig_allocacmp_k272_1 <= ap_const_lv7_0;
        else 
            ap_sig_allocacmp_k272_1 <= k272_fu_96;
        end if; 
    end process;

    icmp_ln12247_fu_428_p2 <= "1" when (ap_sig_allocacmp_k272_1 = ap_const_lv7_40) else "0";

    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_full_n = ap_const_logic_0) and (start_once_reg = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((real_start = ap_const_logic_1) and (start_once_reg = ap_const_logic_0))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

    v6609_0_address0 <= zext_ln12247_fu_440_p1(6 - 1 downto 0);

    v6609_0_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            v6609_0_ce0 <= ap_const_logic_1;
        else 
            v6609_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    v6609_1_address0 <= zext_ln12247_fu_440_p1(6 - 1 downto 0);

    v6609_1_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            v6609_1_ce0 <= ap_const_logic_1;
        else 
            v6609_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    v6609_2_address0 <= zext_ln12247_fu_440_p1(6 - 1 downto 0);

    v6609_2_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            v6609_2_ce0 <= ap_const_logic_1;
        else 
            v6609_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    v6609_3_address0 <= zext_ln12247_fu_440_p1(6 - 1 downto 0);

    v6609_3_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            v6609_3_ce0 <= ap_const_logic_1;
        else 
            v6609_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    v6609_4_address0 <= zext_ln12247_fu_440_p1(6 - 1 downto 0);

    v6609_4_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            v6609_4_ce0 <= ap_const_logic_1;
        else 
            v6609_4_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    v6609_5_address0 <= zext_ln12247_fu_440_p1(6 - 1 downto 0);

    v6609_5_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            v6609_5_ce0 <= ap_const_logic_1;
        else 
            v6609_5_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    v6609_6_address0 <= zext_ln12247_fu_440_p1(6 - 1 downto 0);

    v6609_6_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            v6609_6_ce0 <= ap_const_logic_1;
        else 
            v6609_6_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    v6609_7_address0 <= zext_ln12247_fu_440_p1(6 - 1 downto 0);

    v6609_7_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            v6609_7_ce0 <= ap_const_logic_1;
        else 
            v6609_7_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    v6610_0_address0 <= zext_ln12247_fu_440_p1(6 - 1 downto 0);

    v6610_0_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            v6610_0_ce0 <= ap_const_logic_1;
        else 
            v6610_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    v6610_1_address0 <= zext_ln12247_fu_440_p1(6 - 1 downto 0);

    v6610_1_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            v6610_1_ce0 <= ap_const_logic_1;
        else 
            v6610_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    v6610_2_address0 <= zext_ln12247_fu_440_p1(6 - 1 downto 0);

    v6610_2_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            v6610_2_ce0 <= ap_const_logic_1;
        else 
            v6610_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    v6610_3_address0 <= zext_ln12247_fu_440_p1(6 - 1 downto 0);

    v6610_3_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            v6610_3_ce0 <= ap_const_logic_1;
        else 
            v6610_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    v6610_4_address0 <= zext_ln12247_fu_440_p1(6 - 1 downto 0);

    v6610_4_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            v6610_4_ce0 <= ap_const_logic_1;
        else 
            v6610_4_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    v6610_5_address0 <= zext_ln12247_fu_440_p1(6 - 1 downto 0);

    v6610_5_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            v6610_5_ce0 <= ap_const_logic_1;
        else 
            v6610_5_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    v6610_6_address0 <= zext_ln12247_fu_440_p1(6 - 1 downto 0);

    v6610_6_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            v6610_6_ce0 <= ap_const_logic_1;
        else 
            v6610_6_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    v6610_7_address0 <= zext_ln12247_fu_440_p1(6 - 1 downto 0);

    v6610_7_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            v6610_7_ce0 <= ap_const_logic_1;
        else 
            v6610_7_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    zext_ln12247_fu_440_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_k272_1),64));
end behav;
