name: mdlm
channels:
  - pytorch
  - anaconda
  - nvidia
  - defaults
dependencies:
  - cuda-nvcc=12.4.99
  - jupyter=1.0.0
  - pip=23.3.1
  - python=3.9
  - pytorch-cuda=12.1
  - pip:
      - causal-conv1d==1.1.3.post1
      - datasets==2.18.0
      - einops==0.7.0
      - fsspec==2024.2.0
      - git-lfs==1.6
      - h5py==3.10.0
      - hydra-core==1.3.2
      - ipdb==0.13.13
      - lightning==2.2.1
      - mamba-ssm==1.1.4
      - notebook==7.1.1
      - nvitop==1.3.2
      - omegaconf==2.3.0
      - packaging==23.2
      - pandas==2.2.1
      - rich==13.7.1
      - seaborn==0.13.2
      - scikit-learn==1.4.0
      - timm==0.9.16
      - transformers==4.38.2
      - triton==2.2.0
      - wandb==0.13.5
      - flash-attn==2.5.6