-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity allo_DDitBlock_dataflow_in_loop_l_ni4_Loop_l_store_C_tile_sj4_proc51_Pipeline_l_store_C_tile_sj is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    p_cast : IN STD_LOGIC_VECTOR (9 downto 0);
    local_C4_63_i_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C4_62_i_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C4_61_i_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C4_60_i_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C4_59_i_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C4_58_i_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C4_57_i_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C4_56_i_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C4_55_i_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C4_54_i_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C4_53_i_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C4_52_i_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C4_51_i_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C4_50_i_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C4_49_i_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C4_48_i_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C4_47_i_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C4_46_i_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C4_45_i_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C4_44_i_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C4_43_i_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C4_42_i_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C4_41_i_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C4_40_i_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C4_39_i_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C4_38_i_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C4_37_i_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C4_36_i_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C4_35_i_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C4_34_i_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C4_33_i_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C4_32_i_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C4_31_i_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C4_30_i_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C4_29_i_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C4_28_i_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C4_27_i_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C4_26_i_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C4_25_i_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C4_24_i_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C4_23_i_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C4_22_i_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C4_21_i_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C4_20_i_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C4_19_i_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C4_18_i_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C4_17_i_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C4_16_i_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C4_15_i_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C4_14_i_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C4_13_i_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C4_12_i_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C4_11_i_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C4_10_i_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C4_9_i_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C4_8_i_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C4_7_i_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C4_6_i_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C4_5_i_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C4_4_i_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C4_3_i_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C4_2_i_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C4_1_i_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C4_i_load : IN STD_LOGIC_VECTOR (31 downto 0);
    tmp : IN STD_LOGIC_VECTOR (9 downto 0);
    v6884_address1 : OUT STD_LOGIC_VECTOR (19 downto 0);
    v6884_ce1 : OUT STD_LOGIC;
    v6884_we1 : OUT STD_LOGIC;
    v6884_d1 : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of allo_DDitBlock_dataflow_in_loop_l_ni4_Loop_l_store_C_tile_sj4_proc51_Pipeline_l_store_C_tile_sj is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv7_40 : STD_LOGIC_VECTOR (6 downto 0) := "1000000";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal icmp_ln12495_fu_647_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal zext_ln12499_fu_1100_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal si4_fu_200 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal add_ln12496_fu_1105_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_si4_load : STD_LOGIC_VECTOR (3 downto 0);
    signal sj4_fu_204 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal select_ln12495_1_fu_685_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_sig_allocacmp_sj4_load : STD_LOGIC_VECTOR (3 downto 0);
    signal indvar_flatten_fu_208 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    signal add_ln12495_1_fu_653_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_sig_allocacmp_indvar_flatten_load : STD_LOGIC_VECTOR (6 downto 0);
    signal v6900_fu_1039_p19 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln12496_fu_671_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln12495_fu_665_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal p_cast_cast_fu_625_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln12495_fu_697_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal empty_fu_701_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_i_i_fu_711_p17 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln12495_fu_693_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_i_i_751_fu_751_p17 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_19_i_i_fu_791_p17 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_20_i_i_fu_831_p17 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_21_i_i_fu_871_p17 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_22_i_i_fu_911_p17 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_23_i_i_fu_951_p17 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_24_i_i_fu_991_p17 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln12495_fu_677_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_i_i_fu_711_p19 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_i_i_751_fu_751_p19 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_19_i_i_fu_791_p19 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_20_i_i_fu_831_p19 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_21_i_i_fu_871_p19 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_22_i_i_fu_911_p19 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_23_i_i_fu_951_p19 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_24_i_i_fu_991_p19 : STD_LOGIC_VECTOR (31 downto 0);
    signal v6900_fu_1039_p17 : STD_LOGIC_VECTOR (31 downto 0);
    signal v6900_fu_1039_p18 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln12496_fu_1031_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln12499_fu_1080_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_s_fu_1086_p3 : STD_LOGIC_VECTOR (19 downto 0);
    signal zext_ln12498_fu_707_p1 : STD_LOGIC_VECTOR (19 downto 0);
    signal add_ln12499_1_fu_1094_p2 : STD_LOGIC_VECTOR (19 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal tmp_i_i_fu_711_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_i_i_fu_711_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_i_i_fu_711_p5 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_i_i_fu_711_p7 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_i_i_fu_711_p9 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_i_i_fu_711_p11 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_i_i_fu_711_p13 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_i_i_fu_711_p15 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_i_i_751_fu_751_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_i_i_751_fu_751_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_i_i_751_fu_751_p5 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_i_i_751_fu_751_p7 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_i_i_751_fu_751_p9 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_i_i_751_fu_751_p11 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_i_i_751_fu_751_p13 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_i_i_751_fu_751_p15 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_19_i_i_fu_791_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_19_i_i_fu_791_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_19_i_i_fu_791_p5 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_19_i_i_fu_791_p7 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_19_i_i_fu_791_p9 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_19_i_i_fu_791_p11 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_19_i_i_fu_791_p13 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_19_i_i_fu_791_p15 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_20_i_i_fu_831_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_20_i_i_fu_831_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_20_i_i_fu_831_p5 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_20_i_i_fu_831_p7 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_20_i_i_fu_831_p9 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_20_i_i_fu_831_p11 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_20_i_i_fu_831_p13 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_20_i_i_fu_831_p15 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_21_i_i_fu_871_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_21_i_i_fu_871_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_21_i_i_fu_871_p5 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_21_i_i_fu_871_p7 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_21_i_i_fu_871_p9 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_21_i_i_fu_871_p11 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_21_i_i_fu_871_p13 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_21_i_i_fu_871_p15 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_22_i_i_fu_911_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_22_i_i_fu_911_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_22_i_i_fu_911_p5 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_22_i_i_fu_911_p7 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_22_i_i_fu_911_p9 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_22_i_i_fu_911_p11 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_22_i_i_fu_911_p13 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_22_i_i_fu_911_p15 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_23_i_i_fu_951_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_23_i_i_fu_951_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_23_i_i_fu_951_p5 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_23_i_i_fu_951_p7 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_23_i_i_fu_951_p9 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_23_i_i_fu_951_p11 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_23_i_i_fu_951_p13 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_23_i_i_fu_951_p15 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_24_i_i_fu_991_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_24_i_i_fu_991_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_24_i_i_fu_991_p5 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_24_i_i_fu_991_p7 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_24_i_i_fu_991_p9 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_24_i_i_fu_991_p11 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_24_i_i_fu_991_p13 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_24_i_i_fu_991_p15 : STD_LOGIC_VECTOR (2 downto 0);
    signal v6900_fu_1039_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal v6900_fu_1039_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal v6900_fu_1039_p5 : STD_LOGIC_VECTOR (2 downto 0);
    signal v6900_fu_1039_p7 : STD_LOGIC_VECTOR (2 downto 0);
    signal v6900_fu_1039_p9 : STD_LOGIC_VECTOR (2 downto 0);
    signal v6900_fu_1039_p11 : STD_LOGIC_VECTOR (2 downto 0);
    signal v6900_fu_1039_p13 : STD_LOGIC_VECTOR (2 downto 0);
    signal v6900_fu_1039_p15 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component allo_DDitBlock_sparsemux_17_3_32_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (2 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (2 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (2 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (2 downto 0);
        din3_WIDTH : INTEGER;
        CASE4 : STD_LOGIC_VECTOR (2 downto 0);
        din4_WIDTH : INTEGER;
        CASE5 : STD_LOGIC_VECTOR (2 downto 0);
        din5_WIDTH : INTEGER;
        CASE6 : STD_LOGIC_VECTOR (2 downto 0);
        din6_WIDTH : INTEGER;
        CASE7 : STD_LOGIC_VECTOR (2 downto 0);
        din7_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        din2 : IN STD_LOGIC_VECTOR (31 downto 0);
        din3 : IN STD_LOGIC_VECTOR (31 downto 0);
        din4 : IN STD_LOGIC_VECTOR (31 downto 0);
        din5 : IN STD_LOGIC_VECTOR (31 downto 0);
        din6 : IN STD_LOGIC_VECTOR (31 downto 0);
        din7 : IN STD_LOGIC_VECTOR (31 downto 0);
        def : IN STD_LOGIC_VECTOR (31 downto 0);
        sel : IN STD_LOGIC_VECTOR (2 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component allo_DDitBlock_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    sparsemux_17_3_32_1_1_U2157 : component allo_DDitBlock_sparsemux_17_3_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "000",
        din0_WIDTH => 32,
        CASE1 => "001",
        din1_WIDTH => 32,
        CASE2 => "010",
        din2_WIDTH => 32,
        CASE3 => "011",
        din3_WIDTH => 32,
        CASE4 => "100",
        din4_WIDTH => 32,
        CASE5 => "101",
        din5_WIDTH => 32,
        CASE6 => "110",
        din6_WIDTH => 32,
        CASE7 => "111",
        din7_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 3,
        dout_WIDTH => 32)
    port map (
        din0 => local_C4_63_i_load,
        din1 => local_C4_62_i_load,
        din2 => local_C4_61_i_load,
        din3 => local_C4_60_i_load,
        din4 => local_C4_59_i_load,
        din5 => local_C4_58_i_load,
        din6 => local_C4_57_i_load,
        din7 => local_C4_56_i_load,
        def => tmp_i_i_fu_711_p17,
        sel => trunc_ln12495_fu_693_p1,
        dout => tmp_i_i_fu_711_p19);

    sparsemux_17_3_32_1_1_U2158 : component allo_DDitBlock_sparsemux_17_3_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "000",
        din0_WIDTH => 32,
        CASE1 => "001",
        din1_WIDTH => 32,
        CASE2 => "010",
        din2_WIDTH => 32,
        CASE3 => "011",
        din3_WIDTH => 32,
        CASE4 => "100",
        din4_WIDTH => 32,
        CASE5 => "101",
        din5_WIDTH => 32,
        CASE6 => "110",
        din6_WIDTH => 32,
        CASE7 => "111",
        din7_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 3,
        dout_WIDTH => 32)
    port map (
        din0 => local_C4_55_i_load,
        din1 => local_C4_54_i_load,
        din2 => local_C4_53_i_load,
        din3 => local_C4_52_i_load,
        din4 => local_C4_51_i_load,
        din5 => local_C4_50_i_load,
        din6 => local_C4_49_i_load,
        din7 => local_C4_48_i_load,
        def => tmp_i_i_751_fu_751_p17,
        sel => trunc_ln12495_fu_693_p1,
        dout => tmp_i_i_751_fu_751_p19);

    sparsemux_17_3_32_1_1_U2159 : component allo_DDitBlock_sparsemux_17_3_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "000",
        din0_WIDTH => 32,
        CASE1 => "001",
        din1_WIDTH => 32,
        CASE2 => "010",
        din2_WIDTH => 32,
        CASE3 => "011",
        din3_WIDTH => 32,
        CASE4 => "100",
        din4_WIDTH => 32,
        CASE5 => "101",
        din5_WIDTH => 32,
        CASE6 => "110",
        din6_WIDTH => 32,
        CASE7 => "111",
        din7_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 3,
        dout_WIDTH => 32)
    port map (
        din0 => local_C4_47_i_load,
        din1 => local_C4_46_i_load,
        din2 => local_C4_45_i_load,
        din3 => local_C4_44_i_load,
        din4 => local_C4_43_i_load,
        din5 => local_C4_42_i_load,
        din6 => local_C4_41_i_load,
        din7 => local_C4_40_i_load,
        def => tmp_19_i_i_fu_791_p17,
        sel => trunc_ln12495_fu_693_p1,
        dout => tmp_19_i_i_fu_791_p19);

    sparsemux_17_3_32_1_1_U2160 : component allo_DDitBlock_sparsemux_17_3_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "000",
        din0_WIDTH => 32,
        CASE1 => "001",
        din1_WIDTH => 32,
        CASE2 => "010",
        din2_WIDTH => 32,
        CASE3 => "011",
        din3_WIDTH => 32,
        CASE4 => "100",
        din4_WIDTH => 32,
        CASE5 => "101",
        din5_WIDTH => 32,
        CASE6 => "110",
        din6_WIDTH => 32,
        CASE7 => "111",
        din7_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 3,
        dout_WIDTH => 32)
    port map (
        din0 => local_C4_39_i_load,
        din1 => local_C4_38_i_load,
        din2 => local_C4_37_i_load,
        din3 => local_C4_36_i_load,
        din4 => local_C4_35_i_load,
        din5 => local_C4_34_i_load,
        din6 => local_C4_33_i_load,
        din7 => local_C4_32_i_load,
        def => tmp_20_i_i_fu_831_p17,
        sel => trunc_ln12495_fu_693_p1,
        dout => tmp_20_i_i_fu_831_p19);

    sparsemux_17_3_32_1_1_U2161 : component allo_DDitBlock_sparsemux_17_3_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "000",
        din0_WIDTH => 32,
        CASE1 => "001",
        din1_WIDTH => 32,
        CASE2 => "010",
        din2_WIDTH => 32,
        CASE3 => "011",
        din3_WIDTH => 32,
        CASE4 => "100",
        din4_WIDTH => 32,
        CASE5 => "101",
        din5_WIDTH => 32,
        CASE6 => "110",
        din6_WIDTH => 32,
        CASE7 => "111",
        din7_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 3,
        dout_WIDTH => 32)
    port map (
        din0 => local_C4_31_i_load,
        din1 => local_C4_30_i_load,
        din2 => local_C4_29_i_load,
        din3 => local_C4_28_i_load,
        din4 => local_C4_27_i_load,
        din5 => local_C4_26_i_load,
        din6 => local_C4_25_i_load,
        din7 => local_C4_24_i_load,
        def => tmp_21_i_i_fu_871_p17,
        sel => trunc_ln12495_fu_693_p1,
        dout => tmp_21_i_i_fu_871_p19);

    sparsemux_17_3_32_1_1_U2162 : component allo_DDitBlock_sparsemux_17_3_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "000",
        din0_WIDTH => 32,
        CASE1 => "001",
        din1_WIDTH => 32,
        CASE2 => "010",
        din2_WIDTH => 32,
        CASE3 => "011",
        din3_WIDTH => 32,
        CASE4 => "100",
        din4_WIDTH => 32,
        CASE5 => "101",
        din5_WIDTH => 32,
        CASE6 => "110",
        din6_WIDTH => 32,
        CASE7 => "111",
        din7_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 3,
        dout_WIDTH => 32)
    port map (
        din0 => local_C4_23_i_load,
        din1 => local_C4_22_i_load,
        din2 => local_C4_21_i_load,
        din3 => local_C4_20_i_load,
        din4 => local_C4_19_i_load,
        din5 => local_C4_18_i_load,
        din6 => local_C4_17_i_load,
        din7 => local_C4_16_i_load,
        def => tmp_22_i_i_fu_911_p17,
        sel => trunc_ln12495_fu_693_p1,
        dout => tmp_22_i_i_fu_911_p19);

    sparsemux_17_3_32_1_1_U2163 : component allo_DDitBlock_sparsemux_17_3_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "000",
        din0_WIDTH => 32,
        CASE1 => "001",
        din1_WIDTH => 32,
        CASE2 => "010",
        din2_WIDTH => 32,
        CASE3 => "011",
        din3_WIDTH => 32,
        CASE4 => "100",
        din4_WIDTH => 32,
        CASE5 => "101",
        din5_WIDTH => 32,
        CASE6 => "110",
        din6_WIDTH => 32,
        CASE7 => "111",
        din7_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 3,
        dout_WIDTH => 32)
    port map (
        din0 => local_C4_15_i_load,
        din1 => local_C4_14_i_load,
        din2 => local_C4_13_i_load,
        din3 => local_C4_12_i_load,
        din4 => local_C4_11_i_load,
        din5 => local_C4_10_i_load,
        din6 => local_C4_9_i_load,
        din7 => local_C4_8_i_load,
        def => tmp_23_i_i_fu_951_p17,
        sel => trunc_ln12495_fu_693_p1,
        dout => tmp_23_i_i_fu_951_p19);

    sparsemux_17_3_32_1_1_U2164 : component allo_DDitBlock_sparsemux_17_3_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "000",
        din0_WIDTH => 32,
        CASE1 => "001",
        din1_WIDTH => 32,
        CASE2 => "010",
        din2_WIDTH => 32,
        CASE3 => "011",
        din3_WIDTH => 32,
        CASE4 => "100",
        din4_WIDTH => 32,
        CASE5 => "101",
        din5_WIDTH => 32,
        CASE6 => "110",
        din6_WIDTH => 32,
        CASE7 => "111",
        din7_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 3,
        dout_WIDTH => 32)
    port map (
        din0 => local_C4_7_i_load,
        din1 => local_C4_6_i_load,
        din2 => local_C4_5_i_load,
        din3 => local_C4_4_i_load,
        din4 => local_C4_3_i_load,
        din5 => local_C4_2_i_load,
        din6 => local_C4_1_i_load,
        din7 => local_C4_i_load,
        def => tmp_24_i_i_fu_991_p17,
        sel => trunc_ln12495_fu_693_p1,
        dout => tmp_24_i_i_fu_991_p19);

    sparsemux_17_3_32_1_1_U2165 : component allo_DDitBlock_sparsemux_17_3_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "000",
        din0_WIDTH => 32,
        CASE1 => "001",
        din1_WIDTH => 32,
        CASE2 => "010",
        din2_WIDTH => 32,
        CASE3 => "011",
        din3_WIDTH => 32,
        CASE4 => "100",
        din4_WIDTH => 32,
        CASE5 => "101",
        din5_WIDTH => 32,
        CASE6 => "110",
        din6_WIDTH => 32,
        CASE7 => "111",
        din7_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 3,
        dout_WIDTH => 32)
    port map (
        din0 => tmp_i_i_fu_711_p19,
        din1 => tmp_i_i_751_fu_751_p19,
        din2 => tmp_19_i_i_fu_791_p19,
        din3 => tmp_20_i_i_fu_831_p19,
        din4 => tmp_21_i_i_fu_871_p19,
        din5 => tmp_22_i_i_fu_911_p19,
        din6 => tmp_23_i_i_fu_951_p19,
        din7 => tmp_24_i_i_fu_991_p19,
        def => v6900_fu_1039_p17,
        sel => v6900_fu_1039_p18,
        dout => v6900_fu_1039_p19);

    flow_control_loop_pipe_sequential_init_U : component allo_DDitBlock_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    indvar_flatten_fu_208_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                if ((icmp_ln12495_fu_647_p2 = ap_const_lv1_0)) then 
                    indvar_flatten_fu_208 <= add_ln12495_1_fu_653_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten_fu_208 <= ap_const_lv7_0;
                end if;
            end if; 
        end if;
    end process;

    si4_fu_200_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                if ((icmp_ln12495_fu_647_p2 = ap_const_lv1_0)) then 
                    si4_fu_200 <= add_ln12496_fu_1105_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    si4_fu_200 <= ap_const_lv4_0;
                end if;
            end if; 
        end if;
    end process;

    sj4_fu_204_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                if ((icmp_ln12495_fu_647_p2 = ap_const_lv1_0)) then 
                    sj4_fu_204 <= select_ln12495_1_fu_685_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    sj4_fu_204 <= ap_const_lv4_0;
                end if;
            end if; 
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln12495_1_fu_653_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten_load) + unsigned(ap_const_lv7_1));
    add_ln12495_fu_665_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_sj4_load) + unsigned(ap_const_lv4_1));
    add_ln12496_fu_1105_p2 <= std_logic_vector(unsigned(select_ln12495_fu_677_p3) + unsigned(ap_const_lv4_1));
    add_ln12499_1_fu_1094_p2 <= std_logic_vector(unsigned(tmp_s_fu_1086_p3) + unsigned(zext_ln12498_fu_707_p1));
    add_ln12499_fu_1080_p2 <= std_logic_vector(unsigned(tmp) + unsigned(zext_ln12496_fu_1031_p1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1_pp0_stage0_iter0)
    begin
        if ((ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(ap_start_int)
    begin
                ap_block_state1_pp0_stage0_iter0 <= (ap_start_int = ap_const_logic_0);
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln12495_fu_647_p2)
    begin
        if (((icmp_ln12495_fu_647_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_state1, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten_load_assign_proc : process(ap_CS_fsm_state1, ap_loop_init, indvar_flatten_fu_208)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_indvar_flatten_load <= ap_const_lv7_0;
        else 
            ap_sig_allocacmp_indvar_flatten_load <= indvar_flatten_fu_208;
        end if; 
    end process;


    ap_sig_allocacmp_si4_load_assign_proc : process(ap_CS_fsm_state1, si4_fu_200, ap_loop_init)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_si4_load <= ap_const_lv4_0;
        else 
            ap_sig_allocacmp_si4_load <= si4_fu_200;
        end if; 
    end process;


    ap_sig_allocacmp_sj4_load_assign_proc : process(ap_CS_fsm_state1, ap_loop_init, sj4_fu_204)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_sj4_load <= ap_const_lv4_0;
        else 
            ap_sig_allocacmp_sj4_load <= sj4_fu_204;
        end if; 
    end process;

    empty_fu_701_p2 <= std_logic_vector(unsigned(p_cast_cast_fu_625_p1) + unsigned(zext_ln12495_fu_697_p1));
    icmp_ln12495_fu_647_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten_load = ap_const_lv7_40) else "0";
    icmp_ln12496_fu_671_p2 <= "1" when (ap_sig_allocacmp_si4_load = ap_const_lv4_8) else "0";
    p_cast_cast_fu_625_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_cast),11));
    select_ln12495_1_fu_685_p3 <= 
        add_ln12495_fu_665_p2 when (icmp_ln12496_fu_671_p2(0) = '1') else 
        ap_sig_allocacmp_sj4_load;
    select_ln12495_fu_677_p3 <= 
        ap_const_lv4_0 when (icmp_ln12496_fu_671_p2(0) = '1') else 
        ap_sig_allocacmp_si4_load;
    tmp_19_i_i_fu_791_p17 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    tmp_20_i_i_fu_831_p17 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    tmp_21_i_i_fu_871_p17 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    tmp_22_i_i_fu_911_p17 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    tmp_23_i_i_fu_951_p17 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    tmp_24_i_i_fu_991_p17 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    tmp_i_i_751_fu_751_p17 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    tmp_i_i_fu_711_p17 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    tmp_s_fu_1086_p3 <= (add_ln12499_fu_1080_p2 & ap_const_lv10_0);
    trunc_ln12495_fu_693_p1 <= select_ln12495_1_fu_685_p3(3 - 1 downto 0);
    v6884_address1 <= zext_ln12499_fu_1100_p1(20 - 1 downto 0);

    v6884_ce1_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            v6884_ce1 <= ap_const_logic_1;
        else 
            v6884_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    v6884_d1 <= v6900_fu_1039_p19;

    v6884_we1_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln12495_fu_647_p2)
    begin
        if (((icmp_ln12495_fu_647_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            v6884_we1 <= ap_const_logic_1;
        else 
            v6884_we1 <= ap_const_logic_0;
        end if; 
    end process;

    v6900_fu_1039_p17 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    v6900_fu_1039_p18 <= select_ln12495_fu_677_p3(3 - 1 downto 0);
    zext_ln12495_fu_697_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln12495_1_fu_685_p3),11));
    zext_ln12496_fu_1031_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln12495_fu_677_p3),10));
    zext_ln12498_fu_707_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(empty_fu_701_p2),20));
    zext_ln12499_fu_1100_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln12499_1_fu_1094_p2),64));
end behav;
