// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module allo_DDitBlock_systolic_QKT_Pipeline_l_store_C_tile_sj4_l_si4 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        tmp_16,
        local_C4_load,
        local_C4_1_load,
        local_C4_2_load,
        local_C4_3_load,
        local_C4_4_load,
        local_C4_5_load,
        local_C4_6_load,
        local_C4_7_load,
        local_C4_8_load,
        local_C4_9_load,
        local_C4_10_load,
        local_C4_11_load,
        local_C4_12_load,
        local_C4_13_load,
        local_C4_14_load,
        local_C4_15_load,
        local_C4_16_load,
        local_C4_17_load,
        local_C4_18_load,
        local_C4_19_load,
        local_C4_20_load,
        local_C4_21_load,
        local_C4_22_load,
        local_C4_23_load,
        local_C4_24_load,
        local_C4_25_load,
        local_C4_26_load,
        local_C4_27_load,
        local_C4_28_load,
        local_C4_29_load,
        local_C4_30_load,
        local_C4_31_load,
        local_C4_32_load,
        local_C4_33_load,
        local_C4_34_load,
        local_C4_35_load,
        local_C4_36_load,
        local_C4_37_load,
        local_C4_38_load,
        local_C4_39_load,
        local_C4_40_load,
        local_C4_41_load,
        local_C4_42_load,
        local_C4_43_load,
        local_C4_44_load,
        local_C4_45_load,
        local_C4_46_load,
        local_C4_47_load,
        local_C4_48_load,
        local_C4_49_load,
        local_C4_50_load,
        local_C4_51_load,
        local_C4_52_load,
        local_C4_53_load,
        local_C4_54_load,
        local_C4_55_load,
        local_C4_56_load,
        local_C4_57_load,
        local_C4_58_load,
        local_C4_59_load,
        local_C4_60_load,
        local_C4_61_load,
        local_C4_62_load,
        local_C4_63_load,
        p_mid2,
        v6884_address1,
        v6884_ce1,
        v6884_we1,
        v6884_d1
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [9:0] tmp_16;
input  [31:0] local_C4_load;
input  [31:0] local_C4_1_load;
input  [31:0] local_C4_2_load;
input  [31:0] local_C4_3_load;
input  [31:0] local_C4_4_load;
input  [31:0] local_C4_5_load;
input  [31:0] local_C4_6_load;
input  [31:0] local_C4_7_load;
input  [31:0] local_C4_8_load;
input  [31:0] local_C4_9_load;
input  [31:0] local_C4_10_load;
input  [31:0] local_C4_11_load;
input  [31:0] local_C4_12_load;
input  [31:0] local_C4_13_load;
input  [31:0] local_C4_14_load;
input  [31:0] local_C4_15_load;
input  [31:0] local_C4_16_load;
input  [31:0] local_C4_17_load;
input  [31:0] local_C4_18_load;
input  [31:0] local_C4_19_load;
input  [31:0] local_C4_20_load;
input  [31:0] local_C4_21_load;
input  [31:0] local_C4_22_load;
input  [31:0] local_C4_23_load;
input  [31:0] local_C4_24_load;
input  [31:0] local_C4_25_load;
input  [31:0] local_C4_26_load;
input  [31:0] local_C4_27_load;
input  [31:0] local_C4_28_load;
input  [31:0] local_C4_29_load;
input  [31:0] local_C4_30_load;
input  [31:0] local_C4_31_load;
input  [31:0] local_C4_32_load;
input  [31:0] local_C4_33_load;
input  [31:0] local_C4_34_load;
input  [31:0] local_C4_35_load;
input  [31:0] local_C4_36_load;
input  [31:0] local_C4_37_load;
input  [31:0] local_C4_38_load;
input  [31:0] local_C4_39_load;
input  [31:0] local_C4_40_load;
input  [31:0] local_C4_41_load;
input  [31:0] local_C4_42_load;
input  [31:0] local_C4_43_load;
input  [31:0] local_C4_44_load;
input  [31:0] local_C4_45_load;
input  [31:0] local_C4_46_load;
input  [31:0] local_C4_47_load;
input  [31:0] local_C4_48_load;
input  [31:0] local_C4_49_load;
input  [31:0] local_C4_50_load;
input  [31:0] local_C4_51_load;
input  [31:0] local_C4_52_load;
input  [31:0] local_C4_53_load;
input  [31:0] local_C4_54_load;
input  [31:0] local_C4_55_load;
input  [31:0] local_C4_56_load;
input  [31:0] local_C4_57_load;
input  [31:0] local_C4_58_load;
input  [31:0] local_C4_59_load;
input  [31:0] local_C4_60_load;
input  [31:0] local_C4_61_load;
input  [31:0] local_C4_62_load;
input  [31:0] local_C4_63_load;
input  [9:0] p_mid2;
output  [19:0] v6884_address1;
output   v6884_ce1;
output   v6884_we1;
output  [31:0] v6884_d1;

reg ap_idle;
reg v6884_ce1;
reg v6884_we1;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] icmp_ln12626_fu_641_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [63:0] zext_ln12630_fu_1084_p1;
reg   [3:0] si4_fu_198;
wire   [3:0] add_ln12627_fu_1089_p2;
wire    ap_loop_init;
reg   [3:0] ap_sig_allocacmp_si4_load;
reg   [3:0] sj4_fu_202;
wire   [3:0] select_ln12626_1_fu_679_p3;
reg   [3:0] ap_sig_allocacmp_sj4_load;
reg   [6:0] indvar_flatten13_fu_206;
wire   [6:0] add_ln12626_1_fu_647_p2;
reg   [6:0] ap_sig_allocacmp_indvar_flatten13_load;
wire   [31:0] v6900_fu_1029_p19;
wire   [0:0] icmp_ln12627_fu_665_p2;
wire   [3:0] add_ln12626_fu_659_p2;
wire   [9:0] zext_ln12626_fu_687_p1;
wire   [31:0] tmp_fu_701_p17;
wire   [2:0] trunc_ln12626_fu_691_p1;
wire   [31:0] tmp_9_fu_741_p17;
wire   [31:0] tmp_s_fu_781_p17;
wire   [31:0] tmp_1_fu_821_p17;
wire   [31:0] tmp_2_fu_861_p17;
wire   [31:0] tmp_3_fu_901_p17;
wire   [31:0] tmp_4_fu_941_p17;
wire   [31:0] tmp_5_fu_981_p17;
wire   [3:0] select_ln12626_fu_671_p3;
wire   [31:0] tmp_fu_701_p19;
wire   [31:0] tmp_9_fu_741_p19;
wire   [31:0] tmp_s_fu_781_p19;
wire   [31:0] tmp_1_fu_821_p19;
wire   [31:0] tmp_2_fu_861_p19;
wire   [31:0] tmp_3_fu_901_p19;
wire   [31:0] tmp_4_fu_941_p19;
wire   [31:0] tmp_5_fu_981_p19;
wire   [31:0] v6900_fu_1029_p17;
wire   [2:0] v6900_fu_1029_p18;
wire   [9:0] zext_ln12627_fu_1021_p1;
wire   [9:0] add_ln12630_fu_1070_p2;
wire   [9:0] empty_fu_695_p2;
wire   [19:0] tmp_6_fu_1076_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
wire   [2:0] tmp_fu_701_p1;
wire   [2:0] tmp_fu_701_p3;
wire   [2:0] tmp_fu_701_p5;
wire   [2:0] tmp_fu_701_p7;
wire  signed [2:0] tmp_fu_701_p9;
wire  signed [2:0] tmp_fu_701_p11;
wire  signed [2:0] tmp_fu_701_p13;
wire  signed [2:0] tmp_fu_701_p15;
wire   [2:0] tmp_9_fu_741_p1;
wire   [2:0] tmp_9_fu_741_p3;
wire   [2:0] tmp_9_fu_741_p5;
wire   [2:0] tmp_9_fu_741_p7;
wire  signed [2:0] tmp_9_fu_741_p9;
wire  signed [2:0] tmp_9_fu_741_p11;
wire  signed [2:0] tmp_9_fu_741_p13;
wire  signed [2:0] tmp_9_fu_741_p15;
wire   [2:0] tmp_s_fu_781_p1;
wire   [2:0] tmp_s_fu_781_p3;
wire   [2:0] tmp_s_fu_781_p5;
wire   [2:0] tmp_s_fu_781_p7;
wire  signed [2:0] tmp_s_fu_781_p9;
wire  signed [2:0] tmp_s_fu_781_p11;
wire  signed [2:0] tmp_s_fu_781_p13;
wire  signed [2:0] tmp_s_fu_781_p15;
wire   [2:0] tmp_1_fu_821_p1;
wire   [2:0] tmp_1_fu_821_p3;
wire   [2:0] tmp_1_fu_821_p5;
wire   [2:0] tmp_1_fu_821_p7;
wire  signed [2:0] tmp_1_fu_821_p9;
wire  signed [2:0] tmp_1_fu_821_p11;
wire  signed [2:0] tmp_1_fu_821_p13;
wire  signed [2:0] tmp_1_fu_821_p15;
wire   [2:0] tmp_2_fu_861_p1;
wire   [2:0] tmp_2_fu_861_p3;
wire   [2:0] tmp_2_fu_861_p5;
wire   [2:0] tmp_2_fu_861_p7;
wire  signed [2:0] tmp_2_fu_861_p9;
wire  signed [2:0] tmp_2_fu_861_p11;
wire  signed [2:0] tmp_2_fu_861_p13;
wire  signed [2:0] tmp_2_fu_861_p15;
wire   [2:0] tmp_3_fu_901_p1;
wire   [2:0] tmp_3_fu_901_p3;
wire   [2:0] tmp_3_fu_901_p5;
wire   [2:0] tmp_3_fu_901_p7;
wire  signed [2:0] tmp_3_fu_901_p9;
wire  signed [2:0] tmp_3_fu_901_p11;
wire  signed [2:0] tmp_3_fu_901_p13;
wire  signed [2:0] tmp_3_fu_901_p15;
wire   [2:0] tmp_4_fu_941_p1;
wire   [2:0] tmp_4_fu_941_p3;
wire   [2:0] tmp_4_fu_941_p5;
wire   [2:0] tmp_4_fu_941_p7;
wire  signed [2:0] tmp_4_fu_941_p9;
wire  signed [2:0] tmp_4_fu_941_p11;
wire  signed [2:0] tmp_4_fu_941_p13;
wire  signed [2:0] tmp_4_fu_941_p15;
wire   [2:0] tmp_5_fu_981_p1;
wire   [2:0] tmp_5_fu_981_p3;
wire   [2:0] tmp_5_fu_981_p5;
wire   [2:0] tmp_5_fu_981_p7;
wire  signed [2:0] tmp_5_fu_981_p9;
wire  signed [2:0] tmp_5_fu_981_p11;
wire  signed [2:0] tmp_5_fu_981_p13;
wire  signed [2:0] tmp_5_fu_981_p15;
wire   [2:0] v6900_fu_1029_p1;
wire   [2:0] v6900_fu_1029_p3;
wire   [2:0] v6900_fu_1029_p5;
wire   [2:0] v6900_fu_1029_p7;
wire  signed [2:0] v6900_fu_1029_p9;
wire  signed [2:0] v6900_fu_1029_p11;
wire  signed [2:0] v6900_fu_1029_p13;
wire  signed [2:0] v6900_fu_1029_p15;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 si4_fu_198 = 4'd0;
#0 sj4_fu_202 = 4'd0;
#0 indvar_flatten13_fu_206 = 7'd0;
#0 ap_done_reg = 1'b0;
end

allo_DDitBlock_sparsemux_17_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 32 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 32 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 32 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
sparsemux_17_3_32_1_1_U1996(
    .din0(local_C4_load),
    .din1(local_C4_1_load),
    .din2(local_C4_2_load),
    .din3(local_C4_3_load),
    .din4(local_C4_4_load),
    .din5(local_C4_5_load),
    .din6(local_C4_6_load),
    .din7(local_C4_7_load),
    .def(tmp_fu_701_p17),
    .sel(trunc_ln12626_fu_691_p1),
    .dout(tmp_fu_701_p19)
);

allo_DDitBlock_sparsemux_17_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 32 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 32 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 32 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
sparsemux_17_3_32_1_1_U1997(
    .din0(local_C4_8_load),
    .din1(local_C4_9_load),
    .din2(local_C4_10_load),
    .din3(local_C4_11_load),
    .din4(local_C4_12_load),
    .din5(local_C4_13_load),
    .din6(local_C4_14_load),
    .din7(local_C4_15_load),
    .def(tmp_9_fu_741_p17),
    .sel(trunc_ln12626_fu_691_p1),
    .dout(tmp_9_fu_741_p19)
);

allo_DDitBlock_sparsemux_17_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 32 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 32 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 32 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
sparsemux_17_3_32_1_1_U1998(
    .din0(local_C4_16_load),
    .din1(local_C4_17_load),
    .din2(local_C4_18_load),
    .din3(local_C4_19_load),
    .din4(local_C4_20_load),
    .din5(local_C4_21_load),
    .din6(local_C4_22_load),
    .din7(local_C4_23_load),
    .def(tmp_s_fu_781_p17),
    .sel(trunc_ln12626_fu_691_p1),
    .dout(tmp_s_fu_781_p19)
);

allo_DDitBlock_sparsemux_17_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 32 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 32 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 32 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
sparsemux_17_3_32_1_1_U1999(
    .din0(local_C4_24_load),
    .din1(local_C4_25_load),
    .din2(local_C4_26_load),
    .din3(local_C4_27_load),
    .din4(local_C4_28_load),
    .din5(local_C4_29_load),
    .din6(local_C4_30_load),
    .din7(local_C4_31_load),
    .def(tmp_1_fu_821_p17),
    .sel(trunc_ln12626_fu_691_p1),
    .dout(tmp_1_fu_821_p19)
);

allo_DDitBlock_sparsemux_17_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 32 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 32 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 32 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
sparsemux_17_3_32_1_1_U2000(
    .din0(local_C4_32_load),
    .din1(local_C4_33_load),
    .din2(local_C4_34_load),
    .din3(local_C4_35_load),
    .din4(local_C4_36_load),
    .din5(local_C4_37_load),
    .din6(local_C4_38_load),
    .din7(local_C4_39_load),
    .def(tmp_2_fu_861_p17),
    .sel(trunc_ln12626_fu_691_p1),
    .dout(tmp_2_fu_861_p19)
);

allo_DDitBlock_sparsemux_17_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 32 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 32 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 32 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
sparsemux_17_3_32_1_1_U2001(
    .din0(local_C4_40_load),
    .din1(local_C4_41_load),
    .din2(local_C4_42_load),
    .din3(local_C4_43_load),
    .din4(local_C4_44_load),
    .din5(local_C4_45_load),
    .din6(local_C4_46_load),
    .din7(local_C4_47_load),
    .def(tmp_3_fu_901_p17),
    .sel(trunc_ln12626_fu_691_p1),
    .dout(tmp_3_fu_901_p19)
);

allo_DDitBlock_sparsemux_17_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 32 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 32 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 32 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
sparsemux_17_3_32_1_1_U2002(
    .din0(local_C4_48_load),
    .din1(local_C4_49_load),
    .din2(local_C4_50_load),
    .din3(local_C4_51_load),
    .din4(local_C4_52_load),
    .din5(local_C4_53_load),
    .din6(local_C4_54_load),
    .din7(local_C4_55_load),
    .def(tmp_4_fu_941_p17),
    .sel(trunc_ln12626_fu_691_p1),
    .dout(tmp_4_fu_941_p19)
);

allo_DDitBlock_sparsemux_17_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 32 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 32 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 32 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
sparsemux_17_3_32_1_1_U2003(
    .din0(local_C4_56_load),
    .din1(local_C4_57_load),
    .din2(local_C4_58_load),
    .din3(local_C4_59_load),
    .din4(local_C4_60_load),
    .din5(local_C4_61_load),
    .din6(local_C4_62_load),
    .din7(local_C4_63_load),
    .def(tmp_5_fu_981_p17),
    .sel(trunc_ln12626_fu_691_p1),
    .dout(tmp_5_fu_981_p19)
);

allo_DDitBlock_sparsemux_17_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 32 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 32 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 32 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
sparsemux_17_3_32_1_1_U2004(
    .din0(tmp_fu_701_p19),
    .din1(tmp_9_fu_741_p19),
    .din2(tmp_s_fu_781_p19),
    .din3(tmp_1_fu_821_p19),
    .din4(tmp_2_fu_861_p19),
    .din5(tmp_3_fu_901_p19),
    .din6(tmp_4_fu_941_p19),
    .din7(tmp_5_fu_981_p19),
    .def(v6900_fu_1029_p17),
    .sel(v6900_fu_1029_p18),
    .dout(v6900_fu_1029_p19)
);

allo_DDitBlock_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        if ((icmp_ln12626_fu_641_p2 == 1'd0)) begin
            indvar_flatten13_fu_206 <= add_ln12626_1_fu_647_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten13_fu_206 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        if ((icmp_ln12626_fu_641_p2 == 1'd0)) begin
            si4_fu_198 <= add_ln12627_fu_1089_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            si4_fu_198 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        if ((icmp_ln12626_fu_641_p2 == 1'd0)) begin
            sj4_fu_202 <= select_ln12626_1_fu_679_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            sj4_fu_202 <= 4'd0;
        end
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1_pp0_stage0_iter0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln12626_fu_641_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten13_load = 7'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten13_load = indvar_flatten13_fu_206;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_si4_load = 4'd0;
    end else begin
        ap_sig_allocacmp_si4_load = si4_fu_198;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_sj4_load = 4'd0;
    end else begin
        ap_sig_allocacmp_sj4_load = sj4_fu_202;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        v6884_ce1 = 1'b1;
    end else begin
        v6884_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln12626_fu_641_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        v6884_we1 = 1'b1;
    end else begin
        v6884_we1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln12626_1_fu_647_p2 = (ap_sig_allocacmp_indvar_flatten13_load + 7'd1);

assign add_ln12626_fu_659_p2 = (ap_sig_allocacmp_sj4_load + 4'd1);

assign add_ln12627_fu_1089_p2 = (select_ln12626_fu_671_p3 + 4'd1);

assign add_ln12630_fu_1070_p2 = (p_mid2 + zext_ln12627_fu_1021_p1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start_int == 1'b0);
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign empty_fu_695_p2 = (tmp_16 + zext_ln12626_fu_687_p1);

assign icmp_ln12626_fu_641_p2 = ((ap_sig_allocacmp_indvar_flatten13_load == 7'd64) ? 1'b1 : 1'b0);

assign icmp_ln12627_fu_665_p2 = ((ap_sig_allocacmp_si4_load == 4'd8) ? 1'b1 : 1'b0);

assign select_ln12626_1_fu_679_p3 = ((icmp_ln12627_fu_665_p2[0:0] == 1'b1) ? add_ln12626_fu_659_p2 : ap_sig_allocacmp_sj4_load);

assign select_ln12626_fu_671_p3 = ((icmp_ln12627_fu_665_p2[0:0] == 1'b1) ? 4'd0 : ap_sig_allocacmp_si4_load);

assign tmp_1_fu_821_p17 = 'bx;

assign tmp_2_fu_861_p17 = 'bx;

assign tmp_3_fu_901_p17 = 'bx;

assign tmp_4_fu_941_p17 = 'bx;

assign tmp_5_fu_981_p17 = 'bx;

assign tmp_6_fu_1076_p3 = {{add_ln12630_fu_1070_p2}, {empty_fu_695_p2}};

assign tmp_9_fu_741_p17 = 'bx;

assign tmp_fu_701_p17 = 'bx;

assign tmp_s_fu_781_p17 = 'bx;

assign trunc_ln12626_fu_691_p1 = select_ln12626_1_fu_679_p3[2:0];

assign v6884_address1 = zext_ln12630_fu_1084_p1;

assign v6884_d1 = v6900_fu_1029_p19;

assign v6900_fu_1029_p17 = 'bx;

assign v6900_fu_1029_p18 = select_ln12626_fu_671_p3[2:0];

assign zext_ln12626_fu_687_p1 = select_ln12626_1_fu_679_p3;

assign zext_ln12627_fu_1021_p1 = select_ln12626_fu_671_p3;

assign zext_ln12630_fu_1084_p1 = tmp_6_fu_1076_p3;

endmodule //allo_DDitBlock_systolic_QKT_Pipeline_l_store_C_tile_sj4_l_si4
