-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity allo_DDitBlock_adaLN_modulate is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    v236_0_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    v236_0_ce0 : OUT STD_LOGIC;
    v236_0_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    v237_address0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    v237_ce0 : OUT STD_LOGIC;
    v237_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    v238_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    v238_ce0 : OUT STD_LOGIC;
    v238_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    v239_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    v239_ce0 : OUT STD_LOGIC;
    v239_we0 : OUT STD_LOGIC;
    v239_d0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of allo_DDitBlock_adaLN_modulate is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (8 downto 0) := "000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (8 downto 0) := "000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (8 downto 0) := "000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (8 downto 0) := "000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (8 downto 0) := "000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (8 downto 0) := "001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (8 downto 0) := "010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (8 downto 0) := "100000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv7_40 : STD_LOGIC_VECTOR (6 downto 0) := "1000000";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal v228_fu_211_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal v228_reg_326 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal tmp_s_fu_222_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_s_reg_331 : STD_LOGIC_VECTOR (8 downto 0);
    signal local_A_0_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal local_A_0_ce0 : STD_LOGIC;
    signal local_A_0_we0 : STD_LOGIC;
    signal local_A_0_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal local_B_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal local_B_ce0 : STD_LOGIC;
    signal local_B_we0 : STD_LOGIC;
    signal local_B_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal local_B_1_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal local_B_1_ce0 : STD_LOGIC;
    signal local_B_1_we0 : STD_LOGIC;
    signal local_B_1_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal local_B_2_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal local_B_2_ce0 : STD_LOGIC;
    signal local_B_2_we0 : STD_LOGIC;
    signal local_B_2_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal local_B_3_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal local_B_3_ce0 : STD_LOGIC;
    signal local_B_3_we0 : STD_LOGIC;
    signal local_B_3_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal local_B_4_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal local_B_4_ce0 : STD_LOGIC;
    signal local_B_4_we0 : STD_LOGIC;
    signal local_B_4_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal local_B_5_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal local_B_5_ce0 : STD_LOGIC;
    signal local_B_5_we0 : STD_LOGIC;
    signal local_B_5_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal local_B_6_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal local_B_6_ce0 : STD_LOGIC;
    signal local_B_6_we0 : STD_LOGIC;
    signal local_B_6_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal local_B_7_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal local_B_7_ce0 : STD_LOGIC;
    signal local_B_7_we0 : STD_LOGIC;
    signal local_B_7_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal Y_0_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal Y_0_ce0 : STD_LOGIC;
    signal Y_0_we0 : STD_LOGIC;
    signal Y_0_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal Y_0_ce1 : STD_LOGIC;
    signal Y_0_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_adaLN_modulate_Pipeline_VITIS_LOOP_522_2_fu_118_ap_start : STD_LOGIC;
    signal grp_adaLN_modulate_Pipeline_VITIS_LOOP_522_2_fu_118_ap_done : STD_LOGIC;
    signal grp_adaLN_modulate_Pipeline_VITIS_LOOP_522_2_fu_118_ap_idle : STD_LOGIC;
    signal grp_adaLN_modulate_Pipeline_VITIS_LOOP_522_2_fu_118_ap_ready : STD_LOGIC;
    signal grp_adaLN_modulate_Pipeline_VITIS_LOOP_522_2_fu_118_Y_0_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_adaLN_modulate_Pipeline_VITIS_LOOP_522_2_fu_118_Y_0_ce0 : STD_LOGIC;
    signal grp_adaLN_modulate_Pipeline_VITIS_LOOP_522_2_fu_118_Y_0_we0 : STD_LOGIC;
    signal grp_adaLN_modulate_Pipeline_VITIS_LOOP_522_2_fu_118_Y_0_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_adaLN_modulate_Pipeline_l_load_A_tile_ak_fu_124_ap_start : STD_LOGIC;
    signal grp_adaLN_modulate_Pipeline_l_load_A_tile_ak_fu_124_ap_done : STD_LOGIC;
    signal grp_adaLN_modulate_Pipeline_l_load_A_tile_ak_fu_124_ap_idle : STD_LOGIC;
    signal grp_adaLN_modulate_Pipeline_l_load_A_tile_ak_fu_124_ap_ready : STD_LOGIC;
    signal grp_adaLN_modulate_Pipeline_l_load_A_tile_ak_fu_124_v236_0_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_adaLN_modulate_Pipeline_l_load_A_tile_ak_fu_124_v236_0_ce0 : STD_LOGIC;
    signal grp_adaLN_modulate_Pipeline_l_load_A_tile_ak_fu_124_local_A_0_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_adaLN_modulate_Pipeline_l_load_A_tile_ak_fu_124_local_A_0_ce0 : STD_LOGIC;
    signal grp_adaLN_modulate_Pipeline_l_load_A_tile_ak_fu_124_local_A_0_we0 : STD_LOGIC;
    signal grp_adaLN_modulate_Pipeline_l_load_A_tile_ak_fu_124_local_A_0_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_ap_start : STD_LOGIC;
    signal grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_ap_done : STD_LOGIC;
    signal grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_ap_idle : STD_LOGIC;
    signal grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_ap_ready : STD_LOGIC;
    signal grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_ce0 : STD_LOGIC;
    signal grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_we0 : STD_LOGIC;
    signal grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_1_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_1_ce0 : STD_LOGIC;
    signal grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_1_we0 : STD_LOGIC;
    signal grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_1_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_2_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_2_ce0 : STD_LOGIC;
    signal grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_2_we0 : STD_LOGIC;
    signal grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_2_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_3_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_3_ce0 : STD_LOGIC;
    signal grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_3_we0 : STD_LOGIC;
    signal grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_3_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_4_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_4_ce0 : STD_LOGIC;
    signal grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_4_we0 : STD_LOGIC;
    signal grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_4_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_5_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_5_ce0 : STD_LOGIC;
    signal grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_5_we0 : STD_LOGIC;
    signal grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_5_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_6_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_6_ce0 : STD_LOGIC;
    signal grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_6_we0 : STD_LOGIC;
    signal grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_6_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_7_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_7_ce0 : STD_LOGIC;
    signal grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_7_we0 : STD_LOGIC;
    signal grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_7_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_v237_address0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_v237_ce0 : STD_LOGIC;
    signal grp_adaLN_modulate_Pipeline_l_bias_add_fu_147_ap_start : STD_LOGIC;
    signal grp_adaLN_modulate_Pipeline_l_bias_add_fu_147_ap_done : STD_LOGIC;
    signal grp_adaLN_modulate_Pipeline_l_bias_add_fu_147_ap_idle : STD_LOGIC;
    signal grp_adaLN_modulate_Pipeline_l_bias_add_fu_147_ap_ready : STD_LOGIC;
    signal grp_adaLN_modulate_Pipeline_l_bias_add_fu_147_v238_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_adaLN_modulate_Pipeline_l_bias_add_fu_147_v238_ce0 : STD_LOGIC;
    signal grp_adaLN_modulate_Pipeline_l_bias_add_fu_147_Y_0_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_adaLN_modulate_Pipeline_l_bias_add_fu_147_Y_0_ce0 : STD_LOGIC;
    signal grp_adaLN_modulate_Pipeline_l_bias_add_fu_147_Y_0_we0 : STD_LOGIC;
    signal grp_adaLN_modulate_Pipeline_l_bias_add_fu_147_Y_0_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_adaLN_modulate_Pipeline_l_bias_add_fu_147_Y_0_address1 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_adaLN_modulate_Pipeline_l_bias_add_fu_147_Y_0_ce1 : STD_LOGIC;
    signal grp_adaLN_modulate_Pipeline_l_bias_add_fu_147_v239_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_adaLN_modulate_Pipeline_l_bias_add_fu_147_v239_ce0 : STD_LOGIC;
    signal grp_adaLN_modulate_Pipeline_l_bias_add_fu_147_v239_we0 : STD_LOGIC;
    signal grp_adaLN_modulate_Pipeline_l_bias_add_fu_147_v239_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_systolic_tile_modulate_fu_156_v168_0_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_systolic_tile_modulate_fu_156_v168_0_ce0 : STD_LOGIC;
    signal grp_systolic_tile_modulate_fu_156_v168_0_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_systolic_tile_modulate_fu_156_v168_0_we0 : STD_LOGIC;
    signal grp_systolic_tile_modulate_fu_156_v168_0_address1 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_systolic_tile_modulate_fu_156_v168_0_ce1 : STD_LOGIC;
    signal grp_systolic_tile_modulate_fu_156_v168_0_d1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_systolic_tile_modulate_fu_156_v168_0_we1 : STD_LOGIC;
    signal grp_systolic_tile_modulate_fu_156_v169_0_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_systolic_tile_modulate_fu_156_v169_0_ce0 : STD_LOGIC;
    signal grp_systolic_tile_modulate_fu_156_v169_0_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_systolic_tile_modulate_fu_156_v169_0_we0 : STD_LOGIC;
    signal grp_systolic_tile_modulate_fu_156_v169_0_address1 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_systolic_tile_modulate_fu_156_v169_0_ce1 : STD_LOGIC;
    signal grp_systolic_tile_modulate_fu_156_v169_0_d1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_systolic_tile_modulate_fu_156_v169_0_we1 : STD_LOGIC;
    signal grp_systolic_tile_modulate_fu_156_v169_1_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_systolic_tile_modulate_fu_156_v169_1_ce0 : STD_LOGIC;
    signal grp_systolic_tile_modulate_fu_156_v169_1_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_systolic_tile_modulate_fu_156_v169_1_we0 : STD_LOGIC;
    signal grp_systolic_tile_modulate_fu_156_v169_1_address1 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_systolic_tile_modulate_fu_156_v169_1_ce1 : STD_LOGIC;
    signal grp_systolic_tile_modulate_fu_156_v169_1_d1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_systolic_tile_modulate_fu_156_v169_1_we1 : STD_LOGIC;
    signal grp_systolic_tile_modulate_fu_156_v169_2_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_systolic_tile_modulate_fu_156_v169_2_ce0 : STD_LOGIC;
    signal grp_systolic_tile_modulate_fu_156_v169_2_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_systolic_tile_modulate_fu_156_v169_2_we0 : STD_LOGIC;
    signal grp_systolic_tile_modulate_fu_156_v169_2_address1 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_systolic_tile_modulate_fu_156_v169_2_ce1 : STD_LOGIC;
    signal grp_systolic_tile_modulate_fu_156_v169_2_d1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_systolic_tile_modulate_fu_156_v169_2_we1 : STD_LOGIC;
    signal grp_systolic_tile_modulate_fu_156_v169_3_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_systolic_tile_modulate_fu_156_v169_3_ce0 : STD_LOGIC;
    signal grp_systolic_tile_modulate_fu_156_v169_3_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_systolic_tile_modulate_fu_156_v169_3_we0 : STD_LOGIC;
    signal grp_systolic_tile_modulate_fu_156_v169_3_address1 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_systolic_tile_modulate_fu_156_v169_3_ce1 : STD_LOGIC;
    signal grp_systolic_tile_modulate_fu_156_v169_3_d1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_systolic_tile_modulate_fu_156_v169_3_we1 : STD_LOGIC;
    signal grp_systolic_tile_modulate_fu_156_v169_4_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_systolic_tile_modulate_fu_156_v169_4_ce0 : STD_LOGIC;
    signal grp_systolic_tile_modulate_fu_156_v169_4_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_systolic_tile_modulate_fu_156_v169_4_we0 : STD_LOGIC;
    signal grp_systolic_tile_modulate_fu_156_v169_4_address1 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_systolic_tile_modulate_fu_156_v169_4_ce1 : STD_LOGIC;
    signal grp_systolic_tile_modulate_fu_156_v169_4_d1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_systolic_tile_modulate_fu_156_v169_4_we1 : STD_LOGIC;
    signal grp_systolic_tile_modulate_fu_156_v169_5_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_systolic_tile_modulate_fu_156_v169_5_ce0 : STD_LOGIC;
    signal grp_systolic_tile_modulate_fu_156_v169_5_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_systolic_tile_modulate_fu_156_v169_5_we0 : STD_LOGIC;
    signal grp_systolic_tile_modulate_fu_156_v169_5_address1 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_systolic_tile_modulate_fu_156_v169_5_ce1 : STD_LOGIC;
    signal grp_systolic_tile_modulate_fu_156_v169_5_d1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_systolic_tile_modulate_fu_156_v169_5_we1 : STD_LOGIC;
    signal grp_systolic_tile_modulate_fu_156_v169_6_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_systolic_tile_modulate_fu_156_v169_6_ce0 : STD_LOGIC;
    signal grp_systolic_tile_modulate_fu_156_v169_6_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_systolic_tile_modulate_fu_156_v169_6_we0 : STD_LOGIC;
    signal grp_systolic_tile_modulate_fu_156_v169_6_address1 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_systolic_tile_modulate_fu_156_v169_6_ce1 : STD_LOGIC;
    signal grp_systolic_tile_modulate_fu_156_v169_6_d1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_systolic_tile_modulate_fu_156_v169_6_we1 : STD_LOGIC;
    signal grp_systolic_tile_modulate_fu_156_v169_7_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_systolic_tile_modulate_fu_156_v169_7_ce0 : STD_LOGIC;
    signal grp_systolic_tile_modulate_fu_156_v169_7_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_systolic_tile_modulate_fu_156_v169_7_we0 : STD_LOGIC;
    signal grp_systolic_tile_modulate_fu_156_v169_7_address1 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_systolic_tile_modulate_fu_156_v169_7_ce1 : STD_LOGIC;
    signal grp_systolic_tile_modulate_fu_156_v169_7_d1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_systolic_tile_modulate_fu_156_v169_7_we1 : STD_LOGIC;
    signal grp_systolic_tile_modulate_fu_156_v170_0_0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_systolic_tile_modulate_fu_156_v170_1_0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_systolic_tile_modulate_fu_156_v170_2_0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_systolic_tile_modulate_fu_156_v170_3_0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_systolic_tile_modulate_fu_156_v170_4_0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_systolic_tile_modulate_fu_156_v170_5_0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_systolic_tile_modulate_fu_156_v170_6_0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_systolic_tile_modulate_fu_156_v170_7_0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_systolic_tile_modulate_fu_156_ap_start : STD_LOGIC;
    signal grp_systolic_tile_modulate_fu_156_v170_0_0_ap_vld : STD_LOGIC;
    signal grp_systolic_tile_modulate_fu_156_ap_done : STD_LOGIC;
    signal grp_systolic_tile_modulate_fu_156_v170_1_0_ap_vld : STD_LOGIC;
    signal grp_systolic_tile_modulate_fu_156_v170_2_0_ap_vld : STD_LOGIC;
    signal grp_systolic_tile_modulate_fu_156_v170_3_0_ap_vld : STD_LOGIC;
    signal grp_systolic_tile_modulate_fu_156_v170_4_0_ap_vld : STD_LOGIC;
    signal grp_systolic_tile_modulate_fu_156_v170_5_0_ap_vld : STD_LOGIC;
    signal grp_systolic_tile_modulate_fu_156_v170_6_0_ap_vld : STD_LOGIC;
    signal grp_systolic_tile_modulate_fu_156_v170_7_0_ap_vld : STD_LOGIC;
    signal grp_systolic_tile_modulate_fu_156_ap_ready : STD_LOGIC;
    signal grp_systolic_tile_modulate_fu_156_ap_idle : STD_LOGIC;
    signal grp_systolic_tile_modulate_fu_156_ap_continue : STD_LOGIC;
    signal grp_adaLN_modulate_Pipeline_l_store_C_tile_sj_fu_177_ap_start : STD_LOGIC;
    signal grp_adaLN_modulate_Pipeline_l_store_C_tile_sj_fu_177_ap_done : STD_LOGIC;
    signal grp_adaLN_modulate_Pipeline_l_store_C_tile_sj_fu_177_ap_idle : STD_LOGIC;
    signal grp_adaLN_modulate_Pipeline_l_store_C_tile_sj_fu_177_ap_ready : STD_LOGIC;
    signal grp_adaLN_modulate_Pipeline_l_store_C_tile_sj_fu_177_Y_0_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_adaLN_modulate_Pipeline_l_store_C_tile_sj_fu_177_Y_0_ce0 : STD_LOGIC;
    signal grp_adaLN_modulate_Pipeline_l_store_C_tile_sj_fu_177_Y_0_we0 : STD_LOGIC;
    signal grp_adaLN_modulate_Pipeline_l_store_C_tile_sj_fu_177_Y_0_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_adaLN_modulate_Pipeline_VITIS_LOOP_522_2_fu_118_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_adaLN_modulate_Pipeline_l_load_A_tile_ak_fu_124_ap_start_reg : STD_LOGIC := '0';
    signal icmp_ln423_fu_199_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_ap_start_reg : STD_LOGIC := '0';
    signal grp_adaLN_modulate_Pipeline_l_bias_add_fu_147_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal grp_systolic_tile_modulate_fu_156_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal ap_sync_grp_systolic_tile_modulate_fu_156_ap_ready : STD_LOGIC;
    signal ap_sync_grp_systolic_tile_modulate_fu_156_ap_done : STD_LOGIC;
    signal ap_block_state6_on_subcall_done : BOOLEAN;
    signal ap_sync_reg_grp_systolic_tile_modulate_fu_156_ap_ready : STD_LOGIC := '0';
    signal ap_sync_reg_grp_systolic_tile_modulate_fu_156_ap_done : STD_LOGIC := '0';
    signal local_C_0_fu_82 : STD_LOGIC_VECTOR (31 downto 0);
    signal local_C_0_1_fu_86 : STD_LOGIC_VECTOR (31 downto 0);
    signal local_C_0_2_fu_90 : STD_LOGIC_VECTOR (31 downto 0);
    signal local_C_0_3_fu_94 : STD_LOGIC_VECTOR (31 downto 0);
    signal local_C_0_4_fu_98 : STD_LOGIC_VECTOR (31 downto 0);
    signal local_C_0_5_fu_102 : STD_LOGIC_VECTOR (31 downto 0);
    signal local_C_0_6_fu_106 : STD_LOGIC_VECTOR (31 downto 0);
    signal local_C_0_7_fu_110 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_adaLN_modulate_Pipeline_l_store_C_tile_sj_fu_177_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal ni_fu_42 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    signal add_ln423_fu_205_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal empty_fu_218_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_block_state4_on_subcall_done : BOOLEAN;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component allo_DDitBlock_adaLN_modulate_Pipeline_VITIS_LOOP_522_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        Y_0_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
        Y_0_ce0 : OUT STD_LOGIC;
        Y_0_we0 : OUT STD_LOGIC;
        Y_0_d0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component allo_DDitBlock_adaLN_modulate_Pipeline_l_load_A_tile_ak IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        v228 : IN STD_LOGIC_VECTOR (0 downto 0);
        v236_0_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
        v236_0_ce0 : OUT STD_LOGIC;
        v236_0_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        local_A_0_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
        local_A_0_ce0 : OUT STD_LOGIC;
        local_A_0_we0 : OUT STD_LOGIC;
        local_A_0_d0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component allo_DDitBlock_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        local_B_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
        local_B_ce0 : OUT STD_LOGIC;
        local_B_we0 : OUT STD_LOGIC;
        local_B_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        local_B_1_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
        local_B_1_ce0 : OUT STD_LOGIC;
        local_B_1_we0 : OUT STD_LOGIC;
        local_B_1_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        local_B_2_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
        local_B_2_ce0 : OUT STD_LOGIC;
        local_B_2_we0 : OUT STD_LOGIC;
        local_B_2_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        local_B_3_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
        local_B_3_ce0 : OUT STD_LOGIC;
        local_B_3_we0 : OUT STD_LOGIC;
        local_B_3_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        local_B_4_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
        local_B_4_ce0 : OUT STD_LOGIC;
        local_B_4_we0 : OUT STD_LOGIC;
        local_B_4_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        local_B_5_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
        local_B_5_ce0 : OUT STD_LOGIC;
        local_B_5_we0 : OUT STD_LOGIC;
        local_B_5_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        local_B_6_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
        local_B_6_ce0 : OUT STD_LOGIC;
        local_B_6_we0 : OUT STD_LOGIC;
        local_B_6_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        local_B_7_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
        local_B_7_ce0 : OUT STD_LOGIC;
        local_B_7_we0 : OUT STD_LOGIC;
        local_B_7_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        tmp_104 : IN STD_LOGIC_VECTOR (8 downto 0);
        v237_address0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        v237_ce0 : OUT STD_LOGIC;
        v237_q0 : IN STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component allo_DDitBlock_adaLN_modulate_Pipeline_l_bias_add IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        v238_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
        v238_ce0 : OUT STD_LOGIC;
        v238_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        Y_0_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
        Y_0_ce0 : OUT STD_LOGIC;
        Y_0_we0 : OUT STD_LOGIC;
        Y_0_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        Y_0_address1 : OUT STD_LOGIC_VECTOR (8 downto 0);
        Y_0_ce1 : OUT STD_LOGIC;
        Y_0_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        v239_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
        v239_ce0 : OUT STD_LOGIC;
        v239_we0 : OUT STD_LOGIC;
        v239_d0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component allo_DDitBlock_systolic_tile_modulate IS
    port (
        v168_0_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
        v168_0_ce0 : OUT STD_LOGIC;
        v168_0_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        v168_0_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        v168_0_we0 : OUT STD_LOGIC;
        v168_0_address1 : OUT STD_LOGIC_VECTOR (6 downto 0);
        v168_0_ce1 : OUT STD_LOGIC;
        v168_0_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        v168_0_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        v168_0_we1 : OUT STD_LOGIC;
        v169_0_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
        v169_0_ce0 : OUT STD_LOGIC;
        v169_0_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        v169_0_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        v169_0_we0 : OUT STD_LOGIC;
        v169_0_address1 : OUT STD_LOGIC_VECTOR (6 downto 0);
        v169_0_ce1 : OUT STD_LOGIC;
        v169_0_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        v169_0_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        v169_0_we1 : OUT STD_LOGIC;
        v169_1_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
        v169_1_ce0 : OUT STD_LOGIC;
        v169_1_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        v169_1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        v169_1_we0 : OUT STD_LOGIC;
        v169_1_address1 : OUT STD_LOGIC_VECTOR (6 downto 0);
        v169_1_ce1 : OUT STD_LOGIC;
        v169_1_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        v169_1_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        v169_1_we1 : OUT STD_LOGIC;
        v169_2_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
        v169_2_ce0 : OUT STD_LOGIC;
        v169_2_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        v169_2_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        v169_2_we0 : OUT STD_LOGIC;
        v169_2_address1 : OUT STD_LOGIC_VECTOR (6 downto 0);
        v169_2_ce1 : OUT STD_LOGIC;
        v169_2_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        v169_2_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        v169_2_we1 : OUT STD_LOGIC;
        v169_3_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
        v169_3_ce0 : OUT STD_LOGIC;
        v169_3_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        v169_3_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        v169_3_we0 : OUT STD_LOGIC;
        v169_3_address1 : OUT STD_LOGIC_VECTOR (6 downto 0);
        v169_3_ce1 : OUT STD_LOGIC;
        v169_3_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        v169_3_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        v169_3_we1 : OUT STD_LOGIC;
        v169_4_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
        v169_4_ce0 : OUT STD_LOGIC;
        v169_4_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        v169_4_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        v169_4_we0 : OUT STD_LOGIC;
        v169_4_address1 : OUT STD_LOGIC_VECTOR (6 downto 0);
        v169_4_ce1 : OUT STD_LOGIC;
        v169_4_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        v169_4_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        v169_4_we1 : OUT STD_LOGIC;
        v169_5_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
        v169_5_ce0 : OUT STD_LOGIC;
        v169_5_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        v169_5_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        v169_5_we0 : OUT STD_LOGIC;
        v169_5_address1 : OUT STD_LOGIC_VECTOR (6 downto 0);
        v169_5_ce1 : OUT STD_LOGIC;
        v169_5_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        v169_5_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        v169_5_we1 : OUT STD_LOGIC;
        v169_6_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
        v169_6_ce0 : OUT STD_LOGIC;
        v169_6_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        v169_6_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        v169_6_we0 : OUT STD_LOGIC;
        v169_6_address1 : OUT STD_LOGIC_VECTOR (6 downto 0);
        v169_6_ce1 : OUT STD_LOGIC;
        v169_6_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        v169_6_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        v169_6_we1 : OUT STD_LOGIC;
        v169_7_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
        v169_7_ce0 : OUT STD_LOGIC;
        v169_7_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        v169_7_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        v169_7_we0 : OUT STD_LOGIC;
        v169_7_address1 : OUT STD_LOGIC_VECTOR (6 downto 0);
        v169_7_ce1 : OUT STD_LOGIC;
        v169_7_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        v169_7_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        v169_7_we1 : OUT STD_LOGIC;
        v170_0_0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        v170_1_0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        v170_2_0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        v170_3_0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        v170_4_0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        v170_5_0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        v170_6_0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        v170_7_0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        v170_0_0_ap_vld : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        v170_1_0_ap_vld : OUT STD_LOGIC;
        v170_2_0_ap_vld : OUT STD_LOGIC;
        v170_3_0_ap_vld : OUT STD_LOGIC;
        v170_4_0_ap_vld : OUT STD_LOGIC;
        v170_5_0_ap_vld : OUT STD_LOGIC;
        v170_6_0_ap_vld : OUT STD_LOGIC;
        v170_7_0_ap_vld : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC );
    end component;


    component allo_DDitBlock_adaLN_modulate_Pipeline_l_store_C_tile_sj IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        tmp_104 : IN STD_LOGIC_VECTOR (8 downto 0);
        local_C_0_load : IN STD_LOGIC_VECTOR (31 downto 0);
        local_C_0_1_load : IN STD_LOGIC_VECTOR (31 downto 0);
        local_C_0_2_load : IN STD_LOGIC_VECTOR (31 downto 0);
        local_C_0_3_load : IN STD_LOGIC_VECTOR (31 downto 0);
        local_C_0_4_load : IN STD_LOGIC_VECTOR (31 downto 0);
        local_C_0_5_load : IN STD_LOGIC_VECTOR (31 downto 0);
        local_C_0_6_load : IN STD_LOGIC_VECTOR (31 downto 0);
        local_C_0_7_load : IN STD_LOGIC_VECTOR (31 downto 0);
        Y_0_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
        Y_0_ce0 : OUT STD_LOGIC;
        Y_0_we0 : OUT STD_LOGIC;
        Y_0_d0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component allo_DDitBlock_adaLN_modulate_local_A_0_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (6 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component allo_DDitBlock_adaLN_modulate_Y_0_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (8 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        address1 : IN STD_LOGIC_VECTOR (8 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    local_A_0_U : component allo_DDitBlock_adaLN_modulate_local_A_0_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 128,
        AddressWidth => 7)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => local_A_0_address0,
        ce0 => local_A_0_ce0,
        we0 => local_A_0_we0,
        d0 => grp_adaLN_modulate_Pipeline_l_load_A_tile_ak_fu_124_local_A_0_d0,
        q0 => local_A_0_q0);

    local_B_U : component allo_DDitBlock_adaLN_modulate_local_A_0_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 128,
        AddressWidth => 7)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => local_B_address0,
        ce0 => local_B_ce0,
        we0 => local_B_we0,
        d0 => grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_d0,
        q0 => local_B_q0);

    local_B_1_U : component allo_DDitBlock_adaLN_modulate_local_A_0_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 128,
        AddressWidth => 7)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => local_B_1_address0,
        ce0 => local_B_1_ce0,
        we0 => local_B_1_we0,
        d0 => grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_1_d0,
        q0 => local_B_1_q0);

    local_B_2_U : component allo_DDitBlock_adaLN_modulate_local_A_0_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 128,
        AddressWidth => 7)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => local_B_2_address0,
        ce0 => local_B_2_ce0,
        we0 => local_B_2_we0,
        d0 => grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_2_d0,
        q0 => local_B_2_q0);

    local_B_3_U : component allo_DDitBlock_adaLN_modulate_local_A_0_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 128,
        AddressWidth => 7)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => local_B_3_address0,
        ce0 => local_B_3_ce0,
        we0 => local_B_3_we0,
        d0 => grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_3_d0,
        q0 => local_B_3_q0);

    local_B_4_U : component allo_DDitBlock_adaLN_modulate_local_A_0_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 128,
        AddressWidth => 7)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => local_B_4_address0,
        ce0 => local_B_4_ce0,
        we0 => local_B_4_we0,
        d0 => grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_4_d0,
        q0 => local_B_4_q0);

    local_B_5_U : component allo_DDitBlock_adaLN_modulate_local_A_0_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 128,
        AddressWidth => 7)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => local_B_5_address0,
        ce0 => local_B_5_ce0,
        we0 => local_B_5_we0,
        d0 => grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_5_d0,
        q0 => local_B_5_q0);

    local_B_6_U : component allo_DDitBlock_adaLN_modulate_local_A_0_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 128,
        AddressWidth => 7)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => local_B_6_address0,
        ce0 => local_B_6_ce0,
        we0 => local_B_6_we0,
        d0 => grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_6_d0,
        q0 => local_B_6_q0);

    local_B_7_U : component allo_DDitBlock_adaLN_modulate_local_A_0_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 128,
        AddressWidth => 7)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => local_B_7_address0,
        ce0 => local_B_7_ce0,
        we0 => local_B_7_we0,
        d0 => grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_7_d0,
        q0 => local_B_7_q0);

    Y_0_U : component allo_DDitBlock_adaLN_modulate_Y_0_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 512,
        AddressWidth => 9)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => Y_0_address0,
        ce0 => Y_0_ce0,
        we0 => Y_0_we0,
        d0 => Y_0_d0,
        address1 => grp_adaLN_modulate_Pipeline_l_bias_add_fu_147_Y_0_address1,
        ce1 => Y_0_ce1,
        q1 => Y_0_q1);

    grp_adaLN_modulate_Pipeline_VITIS_LOOP_522_2_fu_118 : component allo_DDitBlock_adaLN_modulate_Pipeline_VITIS_LOOP_522_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_adaLN_modulate_Pipeline_VITIS_LOOP_522_2_fu_118_ap_start,
        ap_done => grp_adaLN_modulate_Pipeline_VITIS_LOOP_522_2_fu_118_ap_done,
        ap_idle => grp_adaLN_modulate_Pipeline_VITIS_LOOP_522_2_fu_118_ap_idle,
        ap_ready => grp_adaLN_modulate_Pipeline_VITIS_LOOP_522_2_fu_118_ap_ready,
        Y_0_address0 => grp_adaLN_modulate_Pipeline_VITIS_LOOP_522_2_fu_118_Y_0_address0,
        Y_0_ce0 => grp_adaLN_modulate_Pipeline_VITIS_LOOP_522_2_fu_118_Y_0_ce0,
        Y_0_we0 => grp_adaLN_modulate_Pipeline_VITIS_LOOP_522_2_fu_118_Y_0_we0,
        Y_0_d0 => grp_adaLN_modulate_Pipeline_VITIS_LOOP_522_2_fu_118_Y_0_d0);

    grp_adaLN_modulate_Pipeline_l_load_A_tile_ak_fu_124 : component allo_DDitBlock_adaLN_modulate_Pipeline_l_load_A_tile_ak
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_adaLN_modulate_Pipeline_l_load_A_tile_ak_fu_124_ap_start,
        ap_done => grp_adaLN_modulate_Pipeline_l_load_A_tile_ak_fu_124_ap_done,
        ap_idle => grp_adaLN_modulate_Pipeline_l_load_A_tile_ak_fu_124_ap_idle,
        ap_ready => grp_adaLN_modulate_Pipeline_l_load_A_tile_ak_fu_124_ap_ready,
        v228 => v228_reg_326,
        v236_0_address0 => grp_adaLN_modulate_Pipeline_l_load_A_tile_ak_fu_124_v236_0_address0,
        v236_0_ce0 => grp_adaLN_modulate_Pipeline_l_load_A_tile_ak_fu_124_v236_0_ce0,
        v236_0_q0 => v236_0_q0,
        local_A_0_address0 => grp_adaLN_modulate_Pipeline_l_load_A_tile_ak_fu_124_local_A_0_address0,
        local_A_0_ce0 => grp_adaLN_modulate_Pipeline_l_load_A_tile_ak_fu_124_local_A_0_ce0,
        local_A_0_we0 => grp_adaLN_modulate_Pipeline_l_load_A_tile_ak_fu_124_local_A_0_we0,
        local_A_0_d0 => grp_adaLN_modulate_Pipeline_l_load_A_tile_ak_fu_124_local_A_0_d0);

    grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132 : component allo_DDitBlock_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_ap_start,
        ap_done => grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_ap_done,
        ap_idle => grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_ap_idle,
        ap_ready => grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_ap_ready,
        local_B_address0 => grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_address0,
        local_B_ce0 => grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_ce0,
        local_B_we0 => grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_we0,
        local_B_d0 => grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_d0,
        local_B_1_address0 => grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_1_address0,
        local_B_1_ce0 => grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_1_ce0,
        local_B_1_we0 => grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_1_we0,
        local_B_1_d0 => grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_1_d0,
        local_B_2_address0 => grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_2_address0,
        local_B_2_ce0 => grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_2_ce0,
        local_B_2_we0 => grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_2_we0,
        local_B_2_d0 => grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_2_d0,
        local_B_3_address0 => grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_3_address0,
        local_B_3_ce0 => grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_3_ce0,
        local_B_3_we0 => grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_3_we0,
        local_B_3_d0 => grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_3_d0,
        local_B_4_address0 => grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_4_address0,
        local_B_4_ce0 => grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_4_ce0,
        local_B_4_we0 => grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_4_we0,
        local_B_4_d0 => grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_4_d0,
        local_B_5_address0 => grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_5_address0,
        local_B_5_ce0 => grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_5_ce0,
        local_B_5_we0 => grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_5_we0,
        local_B_5_d0 => grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_5_d0,
        local_B_6_address0 => grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_6_address0,
        local_B_6_ce0 => grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_6_ce0,
        local_B_6_we0 => grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_6_we0,
        local_B_6_d0 => grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_6_d0,
        local_B_7_address0 => grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_7_address0,
        local_B_7_ce0 => grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_7_ce0,
        local_B_7_we0 => grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_7_we0,
        local_B_7_d0 => grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_7_d0,
        tmp_104 => tmp_s_reg_331,
        v237_address0 => grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_v237_address0,
        v237_ce0 => grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_v237_ce0,
        v237_q0 => v237_q0);

    grp_adaLN_modulate_Pipeline_l_bias_add_fu_147 : component allo_DDitBlock_adaLN_modulate_Pipeline_l_bias_add
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_adaLN_modulate_Pipeline_l_bias_add_fu_147_ap_start,
        ap_done => grp_adaLN_modulate_Pipeline_l_bias_add_fu_147_ap_done,
        ap_idle => grp_adaLN_modulate_Pipeline_l_bias_add_fu_147_ap_idle,
        ap_ready => grp_adaLN_modulate_Pipeline_l_bias_add_fu_147_ap_ready,
        v238_address0 => grp_adaLN_modulate_Pipeline_l_bias_add_fu_147_v238_address0,
        v238_ce0 => grp_adaLN_modulate_Pipeline_l_bias_add_fu_147_v238_ce0,
        v238_q0 => v238_q0,
        Y_0_address0 => grp_adaLN_modulate_Pipeline_l_bias_add_fu_147_Y_0_address0,
        Y_0_ce0 => grp_adaLN_modulate_Pipeline_l_bias_add_fu_147_Y_0_ce0,
        Y_0_we0 => grp_adaLN_modulate_Pipeline_l_bias_add_fu_147_Y_0_we0,
        Y_0_d0 => grp_adaLN_modulate_Pipeline_l_bias_add_fu_147_Y_0_d0,
        Y_0_address1 => grp_adaLN_modulate_Pipeline_l_bias_add_fu_147_Y_0_address1,
        Y_0_ce1 => grp_adaLN_modulate_Pipeline_l_bias_add_fu_147_Y_0_ce1,
        Y_0_q1 => Y_0_q1,
        v239_address0 => grp_adaLN_modulate_Pipeline_l_bias_add_fu_147_v239_address0,
        v239_ce0 => grp_adaLN_modulate_Pipeline_l_bias_add_fu_147_v239_ce0,
        v239_we0 => grp_adaLN_modulate_Pipeline_l_bias_add_fu_147_v239_we0,
        v239_d0 => grp_adaLN_modulate_Pipeline_l_bias_add_fu_147_v239_d0);

    grp_systolic_tile_modulate_fu_156 : component allo_DDitBlock_systolic_tile_modulate
    port map (
        v168_0_address0 => grp_systolic_tile_modulate_fu_156_v168_0_address0,
        v168_0_ce0 => grp_systolic_tile_modulate_fu_156_v168_0_ce0,
        v168_0_d0 => grp_systolic_tile_modulate_fu_156_v168_0_d0,
        v168_0_q0 => local_A_0_q0,
        v168_0_we0 => grp_systolic_tile_modulate_fu_156_v168_0_we0,
        v168_0_address1 => grp_systolic_tile_modulate_fu_156_v168_0_address1,
        v168_0_ce1 => grp_systolic_tile_modulate_fu_156_v168_0_ce1,
        v168_0_d1 => grp_systolic_tile_modulate_fu_156_v168_0_d1,
        v168_0_q1 => ap_const_lv32_0,
        v168_0_we1 => grp_systolic_tile_modulate_fu_156_v168_0_we1,
        v169_0_address0 => grp_systolic_tile_modulate_fu_156_v169_0_address0,
        v169_0_ce0 => grp_systolic_tile_modulate_fu_156_v169_0_ce0,
        v169_0_d0 => grp_systolic_tile_modulate_fu_156_v169_0_d0,
        v169_0_q0 => local_B_q0,
        v169_0_we0 => grp_systolic_tile_modulate_fu_156_v169_0_we0,
        v169_0_address1 => grp_systolic_tile_modulate_fu_156_v169_0_address1,
        v169_0_ce1 => grp_systolic_tile_modulate_fu_156_v169_0_ce1,
        v169_0_d1 => grp_systolic_tile_modulate_fu_156_v169_0_d1,
        v169_0_q1 => ap_const_lv32_0,
        v169_0_we1 => grp_systolic_tile_modulate_fu_156_v169_0_we1,
        v169_1_address0 => grp_systolic_tile_modulate_fu_156_v169_1_address0,
        v169_1_ce0 => grp_systolic_tile_modulate_fu_156_v169_1_ce0,
        v169_1_d0 => grp_systolic_tile_modulate_fu_156_v169_1_d0,
        v169_1_q0 => local_B_1_q0,
        v169_1_we0 => grp_systolic_tile_modulate_fu_156_v169_1_we0,
        v169_1_address1 => grp_systolic_tile_modulate_fu_156_v169_1_address1,
        v169_1_ce1 => grp_systolic_tile_modulate_fu_156_v169_1_ce1,
        v169_1_d1 => grp_systolic_tile_modulate_fu_156_v169_1_d1,
        v169_1_q1 => ap_const_lv32_0,
        v169_1_we1 => grp_systolic_tile_modulate_fu_156_v169_1_we1,
        v169_2_address0 => grp_systolic_tile_modulate_fu_156_v169_2_address0,
        v169_2_ce0 => grp_systolic_tile_modulate_fu_156_v169_2_ce0,
        v169_2_d0 => grp_systolic_tile_modulate_fu_156_v169_2_d0,
        v169_2_q0 => local_B_2_q0,
        v169_2_we0 => grp_systolic_tile_modulate_fu_156_v169_2_we0,
        v169_2_address1 => grp_systolic_tile_modulate_fu_156_v169_2_address1,
        v169_2_ce1 => grp_systolic_tile_modulate_fu_156_v169_2_ce1,
        v169_2_d1 => grp_systolic_tile_modulate_fu_156_v169_2_d1,
        v169_2_q1 => ap_const_lv32_0,
        v169_2_we1 => grp_systolic_tile_modulate_fu_156_v169_2_we1,
        v169_3_address0 => grp_systolic_tile_modulate_fu_156_v169_3_address0,
        v169_3_ce0 => grp_systolic_tile_modulate_fu_156_v169_3_ce0,
        v169_3_d0 => grp_systolic_tile_modulate_fu_156_v169_3_d0,
        v169_3_q0 => local_B_3_q0,
        v169_3_we0 => grp_systolic_tile_modulate_fu_156_v169_3_we0,
        v169_3_address1 => grp_systolic_tile_modulate_fu_156_v169_3_address1,
        v169_3_ce1 => grp_systolic_tile_modulate_fu_156_v169_3_ce1,
        v169_3_d1 => grp_systolic_tile_modulate_fu_156_v169_3_d1,
        v169_3_q1 => ap_const_lv32_0,
        v169_3_we1 => grp_systolic_tile_modulate_fu_156_v169_3_we1,
        v169_4_address0 => grp_systolic_tile_modulate_fu_156_v169_4_address0,
        v169_4_ce0 => grp_systolic_tile_modulate_fu_156_v169_4_ce0,
        v169_4_d0 => grp_systolic_tile_modulate_fu_156_v169_4_d0,
        v169_4_q0 => local_B_4_q0,
        v169_4_we0 => grp_systolic_tile_modulate_fu_156_v169_4_we0,
        v169_4_address1 => grp_systolic_tile_modulate_fu_156_v169_4_address1,
        v169_4_ce1 => grp_systolic_tile_modulate_fu_156_v169_4_ce1,
        v169_4_d1 => grp_systolic_tile_modulate_fu_156_v169_4_d1,
        v169_4_q1 => ap_const_lv32_0,
        v169_4_we1 => grp_systolic_tile_modulate_fu_156_v169_4_we1,
        v169_5_address0 => grp_systolic_tile_modulate_fu_156_v169_5_address0,
        v169_5_ce0 => grp_systolic_tile_modulate_fu_156_v169_5_ce0,
        v169_5_d0 => grp_systolic_tile_modulate_fu_156_v169_5_d0,
        v169_5_q0 => local_B_5_q0,
        v169_5_we0 => grp_systolic_tile_modulate_fu_156_v169_5_we0,
        v169_5_address1 => grp_systolic_tile_modulate_fu_156_v169_5_address1,
        v169_5_ce1 => grp_systolic_tile_modulate_fu_156_v169_5_ce1,
        v169_5_d1 => grp_systolic_tile_modulate_fu_156_v169_5_d1,
        v169_5_q1 => ap_const_lv32_0,
        v169_5_we1 => grp_systolic_tile_modulate_fu_156_v169_5_we1,
        v169_6_address0 => grp_systolic_tile_modulate_fu_156_v169_6_address0,
        v169_6_ce0 => grp_systolic_tile_modulate_fu_156_v169_6_ce0,
        v169_6_d0 => grp_systolic_tile_modulate_fu_156_v169_6_d0,
        v169_6_q0 => local_B_6_q0,
        v169_6_we0 => grp_systolic_tile_modulate_fu_156_v169_6_we0,
        v169_6_address1 => grp_systolic_tile_modulate_fu_156_v169_6_address1,
        v169_6_ce1 => grp_systolic_tile_modulate_fu_156_v169_6_ce1,
        v169_6_d1 => grp_systolic_tile_modulate_fu_156_v169_6_d1,
        v169_6_q1 => ap_const_lv32_0,
        v169_6_we1 => grp_systolic_tile_modulate_fu_156_v169_6_we1,
        v169_7_address0 => grp_systolic_tile_modulate_fu_156_v169_7_address0,
        v169_7_ce0 => grp_systolic_tile_modulate_fu_156_v169_7_ce0,
        v169_7_d0 => grp_systolic_tile_modulate_fu_156_v169_7_d0,
        v169_7_q0 => local_B_7_q0,
        v169_7_we0 => grp_systolic_tile_modulate_fu_156_v169_7_we0,
        v169_7_address1 => grp_systolic_tile_modulate_fu_156_v169_7_address1,
        v169_7_ce1 => grp_systolic_tile_modulate_fu_156_v169_7_ce1,
        v169_7_d1 => grp_systolic_tile_modulate_fu_156_v169_7_d1,
        v169_7_q1 => ap_const_lv32_0,
        v169_7_we1 => grp_systolic_tile_modulate_fu_156_v169_7_we1,
        v170_0_0 => grp_systolic_tile_modulate_fu_156_v170_0_0,
        v170_1_0 => grp_systolic_tile_modulate_fu_156_v170_1_0,
        v170_2_0 => grp_systolic_tile_modulate_fu_156_v170_2_0,
        v170_3_0 => grp_systolic_tile_modulate_fu_156_v170_3_0,
        v170_4_0 => grp_systolic_tile_modulate_fu_156_v170_4_0,
        v170_5_0 => grp_systolic_tile_modulate_fu_156_v170_5_0,
        v170_6_0 => grp_systolic_tile_modulate_fu_156_v170_6_0,
        v170_7_0 => grp_systolic_tile_modulate_fu_156_v170_7_0,
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_systolic_tile_modulate_fu_156_ap_start,
        v170_0_0_ap_vld => grp_systolic_tile_modulate_fu_156_v170_0_0_ap_vld,
        ap_done => grp_systolic_tile_modulate_fu_156_ap_done,
        v170_1_0_ap_vld => grp_systolic_tile_modulate_fu_156_v170_1_0_ap_vld,
        v170_2_0_ap_vld => grp_systolic_tile_modulate_fu_156_v170_2_0_ap_vld,
        v170_3_0_ap_vld => grp_systolic_tile_modulate_fu_156_v170_3_0_ap_vld,
        v170_4_0_ap_vld => grp_systolic_tile_modulate_fu_156_v170_4_0_ap_vld,
        v170_5_0_ap_vld => grp_systolic_tile_modulate_fu_156_v170_5_0_ap_vld,
        v170_6_0_ap_vld => grp_systolic_tile_modulate_fu_156_v170_6_0_ap_vld,
        v170_7_0_ap_vld => grp_systolic_tile_modulate_fu_156_v170_7_0_ap_vld,
        ap_ready => grp_systolic_tile_modulate_fu_156_ap_ready,
        ap_idle => grp_systolic_tile_modulate_fu_156_ap_idle,
        ap_continue => grp_systolic_tile_modulate_fu_156_ap_continue);

    grp_adaLN_modulate_Pipeline_l_store_C_tile_sj_fu_177 : component allo_DDitBlock_adaLN_modulate_Pipeline_l_store_C_tile_sj
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_adaLN_modulate_Pipeline_l_store_C_tile_sj_fu_177_ap_start,
        ap_done => grp_adaLN_modulate_Pipeline_l_store_C_tile_sj_fu_177_ap_done,
        ap_idle => grp_adaLN_modulate_Pipeline_l_store_C_tile_sj_fu_177_ap_idle,
        ap_ready => grp_adaLN_modulate_Pipeline_l_store_C_tile_sj_fu_177_ap_ready,
        tmp_104 => tmp_s_reg_331,
        local_C_0_load => local_C_0_fu_82,
        local_C_0_1_load => local_C_0_1_fu_86,
        local_C_0_2_load => local_C_0_2_fu_90,
        local_C_0_3_load => local_C_0_3_fu_94,
        local_C_0_4_load => local_C_0_4_fu_98,
        local_C_0_5_load => local_C_0_5_fu_102,
        local_C_0_6_load => local_C_0_6_fu_106,
        local_C_0_7_load => local_C_0_7_fu_110,
        Y_0_address0 => grp_adaLN_modulate_Pipeline_l_store_C_tile_sj_fu_177_Y_0_address0,
        Y_0_ce0 => grp_adaLN_modulate_Pipeline_l_store_C_tile_sj_fu_177_Y_0_ce0,
        Y_0_we0 => grp_adaLN_modulate_Pipeline_l_store_C_tile_sj_fu_177_Y_0_we0,
        Y_0_d0 => grp_adaLN_modulate_Pipeline_l_store_C_tile_sj_fu_177_Y_0_d0);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_sync_reg_grp_systolic_tile_modulate_fu_156_ap_done_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_grp_systolic_tile_modulate_fu_156_ap_done <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_state6_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
                    ap_sync_reg_grp_systolic_tile_modulate_fu_156_ap_done <= ap_const_logic_0;
                elsif ((grp_systolic_tile_modulate_fu_156_ap_done = ap_const_logic_1)) then 
                    ap_sync_reg_grp_systolic_tile_modulate_fu_156_ap_done <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_grp_systolic_tile_modulate_fu_156_ap_ready_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_grp_systolic_tile_modulate_fu_156_ap_ready <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_state6_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
                    ap_sync_reg_grp_systolic_tile_modulate_fu_156_ap_ready <= ap_const_logic_0;
                elsif ((grp_systolic_tile_modulate_fu_156_ap_ready = ap_const_logic_1)) then 
                    ap_sync_reg_grp_systolic_tile_modulate_fu_156_ap_ready <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_adaLN_modulate_Pipeline_VITIS_LOOP_522_2_fu_118_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_adaLN_modulate_Pipeline_VITIS_LOOP_522_2_fu_118_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    grp_adaLN_modulate_Pipeline_VITIS_LOOP_522_2_fu_118_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_adaLN_modulate_Pipeline_VITIS_LOOP_522_2_fu_118_ap_ready = ap_const_logic_1)) then 
                    grp_adaLN_modulate_Pipeline_VITIS_LOOP_522_2_fu_118_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_adaLN_modulate_Pipeline_l_bias_add_fu_147_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_adaLN_modulate_Pipeline_l_bias_add_fu_147_ap_start_reg <= ap_const_logic_0;
            else
                if (((icmp_ln423_fu_199_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                    grp_adaLN_modulate_Pipeline_l_bias_add_fu_147_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_adaLN_modulate_Pipeline_l_bias_add_fu_147_ap_ready = ap_const_logic_1)) then 
                    grp_adaLN_modulate_Pipeline_l_bias_add_fu_147_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_adaLN_modulate_Pipeline_l_load_A_tile_ak_fu_124_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_adaLN_modulate_Pipeline_l_load_A_tile_ak_fu_124_ap_start_reg <= ap_const_logic_0;
            else
                if (((icmp_ln423_fu_199_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                    grp_adaLN_modulate_Pipeline_l_load_A_tile_ak_fu_124_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_adaLN_modulate_Pipeline_l_load_A_tile_ak_fu_124_ap_ready = ap_const_logic_1)) then 
                    grp_adaLN_modulate_Pipeline_l_load_A_tile_ak_fu_124_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_ap_start_reg <= ap_const_logic_0;
            else
                if (((icmp_ln423_fu_199_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                    grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_ap_ready = ap_const_logic_1)) then 
                    grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_adaLN_modulate_Pipeline_l_store_C_tile_sj_fu_177_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_adaLN_modulate_Pipeline_l_store_C_tile_sj_fu_177_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
                    grp_adaLN_modulate_Pipeline_l_store_C_tile_sj_fu_177_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_adaLN_modulate_Pipeline_l_store_C_tile_sj_fu_177_ap_ready = ap_const_logic_1)) then 
                    grp_adaLN_modulate_Pipeline_l_store_C_tile_sj_fu_177_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_systolic_tile_modulate_fu_156_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_systolic_tile_modulate_fu_156_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state5) or ((ap_sync_grp_systolic_tile_modulate_fu_156_ap_ready = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state6)))) then 
                    grp_systolic_tile_modulate_fu_156_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_systolic_tile_modulate_fu_156_ap_ready = ap_const_logic_1)) then 
                    grp_systolic_tile_modulate_fu_156_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ni_fu_42_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                ni_fu_42 <= ap_const_lv7_0;
            elsif (((icmp_ln423_fu_199_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                ni_fu_42 <= add_ln423_fu_205_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_systolic_tile_modulate_fu_156_v170_1_0_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then
                local_C_0_1_fu_86 <= grp_systolic_tile_modulate_fu_156_v170_1_0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_systolic_tile_modulate_fu_156_v170_2_0_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then
                local_C_0_2_fu_90 <= grp_systolic_tile_modulate_fu_156_v170_2_0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_systolic_tile_modulate_fu_156_v170_3_0_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then
                local_C_0_3_fu_94 <= grp_systolic_tile_modulate_fu_156_v170_3_0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_systolic_tile_modulate_fu_156_v170_4_0_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then
                local_C_0_4_fu_98 <= grp_systolic_tile_modulate_fu_156_v170_4_0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_systolic_tile_modulate_fu_156_v170_5_0_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then
                local_C_0_5_fu_102 <= grp_systolic_tile_modulate_fu_156_v170_5_0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_systolic_tile_modulate_fu_156_v170_6_0_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then
                local_C_0_6_fu_106 <= grp_systolic_tile_modulate_fu_156_v170_6_0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_systolic_tile_modulate_fu_156_v170_7_0_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then
                local_C_0_7_fu_110 <= grp_systolic_tile_modulate_fu_156_v170_7_0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_systolic_tile_modulate_fu_156_v170_0_0_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then
                local_C_0_fu_82 <= grp_systolic_tile_modulate_fu_156_v170_0_0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                    tmp_s_reg_331(8 downto 3) <= tmp_s_fu_222_p3(8 downto 3);
                v228_reg_326 <= v228_fu_211_p2;
            end if;
        end if;
    end process;
    tmp_s_reg_331(2 downto 0) <= "000";

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state3, grp_adaLN_modulate_Pipeline_VITIS_LOOP_522_2_fu_118_ap_done, grp_adaLN_modulate_Pipeline_l_bias_add_fu_147_ap_done, grp_adaLN_modulate_Pipeline_l_store_C_tile_sj_fu_177_ap_done, ap_CS_fsm_state2, icmp_ln423_fu_199_p2, ap_CS_fsm_state4, ap_CS_fsm_state9, ap_CS_fsm_state6, ap_block_state6_on_subcall_done, ap_CS_fsm_state8, ap_block_state4_on_subcall_done)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_adaLN_modulate_Pipeline_VITIS_LOOP_522_2_fu_118_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                if (((icmp_ln423_fu_199_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state9;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state4 => 
                if (((ap_const_boolean_0 = ap_block_state4_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                if (((ap_const_boolean_0 = ap_block_state6_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state6))) then
                    ap_NS_fsm <= ap_ST_fsm_state7;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                if (((grp_adaLN_modulate_Pipeline_l_store_C_tile_sj_fu_177_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state8;
                end if;
            when ap_ST_fsm_state9 => 
                if (((grp_adaLN_modulate_Pipeline_l_bias_add_fu_147_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state9))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state9;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXX";
        end case;
    end process;

    Y_0_address0_assign_proc : process(grp_adaLN_modulate_Pipeline_VITIS_LOOP_522_2_fu_118_Y_0_address0, grp_adaLN_modulate_Pipeline_l_bias_add_fu_147_Y_0_address0, grp_adaLN_modulate_Pipeline_l_store_C_tile_sj_fu_177_Y_0_address0, ap_CS_fsm_state2, ap_CS_fsm_state9, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            Y_0_address0 <= grp_adaLN_modulate_Pipeline_l_store_C_tile_sj_fu_177_Y_0_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            Y_0_address0 <= grp_adaLN_modulate_Pipeline_l_bias_add_fu_147_Y_0_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            Y_0_address0 <= grp_adaLN_modulate_Pipeline_VITIS_LOOP_522_2_fu_118_Y_0_address0;
        else 
            Y_0_address0 <= "XXXXXXXXX";
        end if; 
    end process;


    Y_0_ce0_assign_proc : process(grp_adaLN_modulate_Pipeline_VITIS_LOOP_522_2_fu_118_Y_0_ce0, grp_adaLN_modulate_Pipeline_l_bias_add_fu_147_Y_0_ce0, grp_adaLN_modulate_Pipeline_l_store_C_tile_sj_fu_177_Y_0_ce0, ap_CS_fsm_state2, ap_CS_fsm_state9, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            Y_0_ce0 <= grp_adaLN_modulate_Pipeline_l_store_C_tile_sj_fu_177_Y_0_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            Y_0_ce0 <= grp_adaLN_modulate_Pipeline_l_bias_add_fu_147_Y_0_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            Y_0_ce0 <= grp_adaLN_modulate_Pipeline_VITIS_LOOP_522_2_fu_118_Y_0_ce0;
        else 
            Y_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    Y_0_ce1_assign_proc : process(grp_adaLN_modulate_Pipeline_l_bias_add_fu_147_Y_0_ce1, ap_CS_fsm_state9)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            Y_0_ce1 <= grp_adaLN_modulate_Pipeline_l_bias_add_fu_147_Y_0_ce1;
        else 
            Y_0_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    Y_0_d0_assign_proc : process(grp_adaLN_modulate_Pipeline_VITIS_LOOP_522_2_fu_118_Y_0_d0, grp_adaLN_modulate_Pipeline_l_bias_add_fu_147_Y_0_d0, grp_adaLN_modulate_Pipeline_l_store_C_tile_sj_fu_177_Y_0_d0, ap_CS_fsm_state2, ap_CS_fsm_state9, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            Y_0_d0 <= grp_adaLN_modulate_Pipeline_l_store_C_tile_sj_fu_177_Y_0_d0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            Y_0_d0 <= grp_adaLN_modulate_Pipeline_l_bias_add_fu_147_Y_0_d0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            Y_0_d0 <= grp_adaLN_modulate_Pipeline_VITIS_LOOP_522_2_fu_118_Y_0_d0;
        else 
            Y_0_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    Y_0_we0_assign_proc : process(grp_adaLN_modulate_Pipeline_VITIS_LOOP_522_2_fu_118_Y_0_we0, grp_adaLN_modulate_Pipeline_l_bias_add_fu_147_Y_0_we0, grp_adaLN_modulate_Pipeline_l_store_C_tile_sj_fu_177_Y_0_we0, ap_CS_fsm_state2, ap_CS_fsm_state9, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            Y_0_we0 <= grp_adaLN_modulate_Pipeline_l_store_C_tile_sj_fu_177_Y_0_we0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            Y_0_we0 <= grp_adaLN_modulate_Pipeline_l_bias_add_fu_147_Y_0_we0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            Y_0_we0 <= grp_adaLN_modulate_Pipeline_VITIS_LOOP_522_2_fu_118_Y_0_we0;
        else 
            Y_0_we0 <= ap_const_logic_0;
        end if; 
    end process;

    add_ln423_fu_205_p2 <= std_logic_vector(unsigned(ni_fu_42) + unsigned(ap_const_lv7_1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(grp_adaLN_modulate_Pipeline_VITIS_LOOP_522_2_fu_118_ap_done)
    begin
        if ((grp_adaLN_modulate_Pipeline_VITIS_LOOP_522_2_fu_118_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(ap_block_state4_on_subcall_done)
    begin
        if ((ap_const_boolean_1 = ap_block_state4_on_subcall_done)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state5_blk <= ap_const_logic_0;

    ap_ST_fsm_state6_blk_assign_proc : process(ap_block_state6_on_subcall_done)
    begin
        if ((ap_const_boolean_1 = ap_block_state6_on_subcall_done)) then 
            ap_ST_fsm_state6_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state6_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state7_blk <= ap_const_logic_0;

    ap_ST_fsm_state8_blk_assign_proc : process(grp_adaLN_modulate_Pipeline_l_store_C_tile_sj_fu_177_ap_done)
    begin
        if ((grp_adaLN_modulate_Pipeline_l_store_C_tile_sj_fu_177_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state8_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state8_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state9_blk_assign_proc : process(grp_adaLN_modulate_Pipeline_l_bias_add_fu_147_ap_done)
    begin
        if ((grp_adaLN_modulate_Pipeline_l_bias_add_fu_147_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state9_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state9_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state4_on_subcall_done_assign_proc : process(grp_adaLN_modulate_Pipeline_l_load_A_tile_ak_fu_124_ap_done, grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_ap_done)
    begin
                ap_block_state4_on_subcall_done <= ((grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_ap_done = ap_const_logic_0) or (grp_adaLN_modulate_Pipeline_l_load_A_tile_ak_fu_124_ap_done = ap_const_logic_0));
    end process;


    ap_block_state6_on_subcall_done_assign_proc : process(ap_sync_grp_systolic_tile_modulate_fu_156_ap_ready, ap_sync_grp_systolic_tile_modulate_fu_156_ap_done)
    begin
                ap_block_state6_on_subcall_done <= ((ap_sync_grp_systolic_tile_modulate_fu_156_ap_ready and ap_sync_grp_systolic_tile_modulate_fu_156_ap_done) = ap_const_logic_0);
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, grp_adaLN_modulate_Pipeline_l_bias_add_fu_147_ap_done, ap_CS_fsm_state9)
    begin
        if ((((grp_adaLN_modulate_Pipeline_l_bias_add_fu_147_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state9)) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(grp_adaLN_modulate_Pipeline_l_bias_add_fu_147_ap_done, ap_CS_fsm_state9)
    begin
        if (((grp_adaLN_modulate_Pipeline_l_bias_add_fu_147_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    ap_sync_grp_systolic_tile_modulate_fu_156_ap_done <= (grp_systolic_tile_modulate_fu_156_ap_done or ap_sync_reg_grp_systolic_tile_modulate_fu_156_ap_done);
    ap_sync_grp_systolic_tile_modulate_fu_156_ap_ready <= (grp_systolic_tile_modulate_fu_156_ap_ready or ap_sync_reg_grp_systolic_tile_modulate_fu_156_ap_ready);
    empty_fu_218_p1 <= ni_fu_42(6 - 1 downto 0);
    grp_adaLN_modulate_Pipeline_VITIS_LOOP_522_2_fu_118_ap_start <= grp_adaLN_modulate_Pipeline_VITIS_LOOP_522_2_fu_118_ap_start_reg;
    grp_adaLN_modulate_Pipeline_l_bias_add_fu_147_ap_start <= grp_adaLN_modulate_Pipeline_l_bias_add_fu_147_ap_start_reg;
    grp_adaLN_modulate_Pipeline_l_load_A_tile_ak_fu_124_ap_start <= grp_adaLN_modulate_Pipeline_l_load_A_tile_ak_fu_124_ap_start_reg;
    grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_ap_start <= grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_ap_start_reg;
    grp_adaLN_modulate_Pipeline_l_store_C_tile_sj_fu_177_ap_start <= grp_adaLN_modulate_Pipeline_l_store_C_tile_sj_fu_177_ap_start_reg;

    grp_systolic_tile_modulate_fu_156_ap_continue_assign_proc : process(ap_CS_fsm_state6, ap_block_state6_on_subcall_done)
    begin
        if (((ap_const_boolean_0 = ap_block_state6_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            grp_systolic_tile_modulate_fu_156_ap_continue <= ap_const_logic_1;
        else 
            grp_systolic_tile_modulate_fu_156_ap_continue <= ap_const_logic_0;
        end if; 
    end process;

    grp_systolic_tile_modulate_fu_156_ap_start <= grp_systolic_tile_modulate_fu_156_ap_start_reg;
    icmp_ln423_fu_199_p2 <= "1" when (ni_fu_42 = ap_const_lv7_40) else "0";

    local_A_0_address0_assign_proc : process(grp_adaLN_modulate_Pipeline_l_load_A_tile_ak_fu_124_local_A_0_address0, grp_systolic_tile_modulate_fu_156_v168_0_address0, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            local_A_0_address0 <= grp_systolic_tile_modulate_fu_156_v168_0_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            local_A_0_address0 <= grp_adaLN_modulate_Pipeline_l_load_A_tile_ak_fu_124_local_A_0_address0;
        else 
            local_A_0_address0 <= "XXXXXXX";
        end if; 
    end process;


    local_A_0_ce0_assign_proc : process(grp_adaLN_modulate_Pipeline_l_load_A_tile_ak_fu_124_local_A_0_ce0, grp_systolic_tile_modulate_fu_156_v168_0_ce0, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            local_A_0_ce0 <= grp_systolic_tile_modulate_fu_156_v168_0_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            local_A_0_ce0 <= grp_adaLN_modulate_Pipeline_l_load_A_tile_ak_fu_124_local_A_0_ce0;
        else 
            local_A_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    local_A_0_we0_assign_proc : process(grp_adaLN_modulate_Pipeline_l_load_A_tile_ak_fu_124_local_A_0_we0, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            local_A_0_we0 <= grp_adaLN_modulate_Pipeline_l_load_A_tile_ak_fu_124_local_A_0_we0;
        else 
            local_A_0_we0 <= ap_const_logic_0;
        end if; 
    end process;


    local_B_1_address0_assign_proc : process(grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_1_address0, grp_systolic_tile_modulate_fu_156_v169_1_address0, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            local_B_1_address0 <= grp_systolic_tile_modulate_fu_156_v169_1_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            local_B_1_address0 <= grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_1_address0;
        else 
            local_B_1_address0 <= "XXXXXXX";
        end if; 
    end process;


    local_B_1_ce0_assign_proc : process(grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_1_ce0, grp_systolic_tile_modulate_fu_156_v169_1_ce0, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            local_B_1_ce0 <= grp_systolic_tile_modulate_fu_156_v169_1_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            local_B_1_ce0 <= grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_1_ce0;
        else 
            local_B_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    local_B_1_we0_assign_proc : process(grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_1_we0, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            local_B_1_we0 <= grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_1_we0;
        else 
            local_B_1_we0 <= ap_const_logic_0;
        end if; 
    end process;


    local_B_2_address0_assign_proc : process(grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_2_address0, grp_systolic_tile_modulate_fu_156_v169_2_address0, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            local_B_2_address0 <= grp_systolic_tile_modulate_fu_156_v169_2_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            local_B_2_address0 <= grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_2_address0;
        else 
            local_B_2_address0 <= "XXXXXXX";
        end if; 
    end process;


    local_B_2_ce0_assign_proc : process(grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_2_ce0, grp_systolic_tile_modulate_fu_156_v169_2_ce0, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            local_B_2_ce0 <= grp_systolic_tile_modulate_fu_156_v169_2_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            local_B_2_ce0 <= grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_2_ce0;
        else 
            local_B_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    local_B_2_we0_assign_proc : process(grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_2_we0, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            local_B_2_we0 <= grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_2_we0;
        else 
            local_B_2_we0 <= ap_const_logic_0;
        end if; 
    end process;


    local_B_3_address0_assign_proc : process(grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_3_address0, grp_systolic_tile_modulate_fu_156_v169_3_address0, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            local_B_3_address0 <= grp_systolic_tile_modulate_fu_156_v169_3_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            local_B_3_address0 <= grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_3_address0;
        else 
            local_B_3_address0 <= "XXXXXXX";
        end if; 
    end process;


    local_B_3_ce0_assign_proc : process(grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_3_ce0, grp_systolic_tile_modulate_fu_156_v169_3_ce0, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            local_B_3_ce0 <= grp_systolic_tile_modulate_fu_156_v169_3_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            local_B_3_ce0 <= grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_3_ce0;
        else 
            local_B_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    local_B_3_we0_assign_proc : process(grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_3_we0, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            local_B_3_we0 <= grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_3_we0;
        else 
            local_B_3_we0 <= ap_const_logic_0;
        end if; 
    end process;


    local_B_4_address0_assign_proc : process(grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_4_address0, grp_systolic_tile_modulate_fu_156_v169_4_address0, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            local_B_4_address0 <= grp_systolic_tile_modulate_fu_156_v169_4_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            local_B_4_address0 <= grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_4_address0;
        else 
            local_B_4_address0 <= "XXXXXXX";
        end if; 
    end process;


    local_B_4_ce0_assign_proc : process(grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_4_ce0, grp_systolic_tile_modulate_fu_156_v169_4_ce0, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            local_B_4_ce0 <= grp_systolic_tile_modulate_fu_156_v169_4_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            local_B_4_ce0 <= grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_4_ce0;
        else 
            local_B_4_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    local_B_4_we0_assign_proc : process(grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_4_we0, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            local_B_4_we0 <= grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_4_we0;
        else 
            local_B_4_we0 <= ap_const_logic_0;
        end if; 
    end process;


    local_B_5_address0_assign_proc : process(grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_5_address0, grp_systolic_tile_modulate_fu_156_v169_5_address0, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            local_B_5_address0 <= grp_systolic_tile_modulate_fu_156_v169_5_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            local_B_5_address0 <= grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_5_address0;
        else 
            local_B_5_address0 <= "XXXXXXX";
        end if; 
    end process;


    local_B_5_ce0_assign_proc : process(grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_5_ce0, grp_systolic_tile_modulate_fu_156_v169_5_ce0, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            local_B_5_ce0 <= grp_systolic_tile_modulate_fu_156_v169_5_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            local_B_5_ce0 <= grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_5_ce0;
        else 
            local_B_5_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    local_B_5_we0_assign_proc : process(grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_5_we0, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            local_B_5_we0 <= grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_5_we0;
        else 
            local_B_5_we0 <= ap_const_logic_0;
        end if; 
    end process;


    local_B_6_address0_assign_proc : process(grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_6_address0, grp_systolic_tile_modulate_fu_156_v169_6_address0, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            local_B_6_address0 <= grp_systolic_tile_modulate_fu_156_v169_6_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            local_B_6_address0 <= grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_6_address0;
        else 
            local_B_6_address0 <= "XXXXXXX";
        end if; 
    end process;


    local_B_6_ce0_assign_proc : process(grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_6_ce0, grp_systolic_tile_modulate_fu_156_v169_6_ce0, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            local_B_6_ce0 <= grp_systolic_tile_modulate_fu_156_v169_6_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            local_B_6_ce0 <= grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_6_ce0;
        else 
            local_B_6_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    local_B_6_we0_assign_proc : process(grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_6_we0, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            local_B_6_we0 <= grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_6_we0;
        else 
            local_B_6_we0 <= ap_const_logic_0;
        end if; 
    end process;


    local_B_7_address0_assign_proc : process(grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_7_address0, grp_systolic_tile_modulate_fu_156_v169_7_address0, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            local_B_7_address0 <= grp_systolic_tile_modulate_fu_156_v169_7_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            local_B_7_address0 <= grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_7_address0;
        else 
            local_B_7_address0 <= "XXXXXXX";
        end if; 
    end process;


    local_B_7_ce0_assign_proc : process(grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_7_ce0, grp_systolic_tile_modulate_fu_156_v169_7_ce0, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            local_B_7_ce0 <= grp_systolic_tile_modulate_fu_156_v169_7_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            local_B_7_ce0 <= grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_7_ce0;
        else 
            local_B_7_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    local_B_7_we0_assign_proc : process(grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_7_we0, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            local_B_7_we0 <= grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_7_we0;
        else 
            local_B_7_we0 <= ap_const_logic_0;
        end if; 
    end process;


    local_B_address0_assign_proc : process(grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_address0, grp_systolic_tile_modulate_fu_156_v169_0_address0, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            local_B_address0 <= grp_systolic_tile_modulate_fu_156_v169_0_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            local_B_address0 <= grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_address0;
        else 
            local_B_address0 <= "XXXXXXX";
        end if; 
    end process;


    local_B_ce0_assign_proc : process(grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_ce0, grp_systolic_tile_modulate_fu_156_v169_0_ce0, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            local_B_ce0 <= grp_systolic_tile_modulate_fu_156_v169_0_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            local_B_ce0 <= grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_ce0;
        else 
            local_B_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    local_B_we0_assign_proc : process(grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_we0, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            local_B_we0 <= grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_local_B_we0;
        else 
            local_B_we0 <= ap_const_logic_0;
        end if; 
    end process;

    tmp_s_fu_222_p3 <= (empty_fu_218_p1 & ap_const_lv3_0);
    v228_fu_211_p2 <= "1" when (ni_fu_42 = ap_const_lv7_0) else "0";
    v236_0_address0 <= grp_adaLN_modulate_Pipeline_l_load_A_tile_ak_fu_124_v236_0_address0;
    v236_0_ce0 <= grp_adaLN_modulate_Pipeline_l_load_A_tile_ak_fu_124_v236_0_ce0;
    v237_address0 <= grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_v237_address0;
    v237_ce0 <= grp_adaLN_modulate_Pipeline_l_load_B_tile_bk_l_bj_fu_132_v237_ce0;
    v238_address0 <= grp_adaLN_modulate_Pipeline_l_bias_add_fu_147_v238_address0;
    v238_ce0 <= grp_adaLN_modulate_Pipeline_l_bias_add_fu_147_v238_ce0;
    v239_address0 <= grp_adaLN_modulate_Pipeline_l_bias_add_fu_147_v239_address0;
    v239_ce0 <= grp_adaLN_modulate_Pipeline_l_bias_add_fu_147_v239_ce0;
    v239_d0 <= grp_adaLN_modulate_Pipeline_l_bias_add_fu_147_v239_d0;
    v239_we0 <= grp_adaLN_modulate_Pipeline_l_bias_add_fu_147_v239_we0;
end behav;
