-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity allo_DDitBlock_systolic_Q_Pipeline_l_store_C_tile_sj1_l_si1 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    tmp_22 : IN STD_LOGIC_VECTOR (8 downto 0);
    local_C1_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C1_1_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C1_2_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C1_3_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C1_4_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C1_5_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C1_6_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C1_7_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C1_8_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C1_9_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C1_10_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C1_11_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C1_12_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C1_13_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C1_14_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C1_15_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C1_16_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C1_17_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C1_18_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C1_19_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C1_20_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C1_21_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C1_22_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C1_23_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C1_24_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C1_25_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C1_26_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C1_27_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C1_28_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C1_29_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C1_30_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C1_31_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C1_32_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C1_33_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C1_34_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C1_35_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C1_36_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C1_37_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C1_38_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C1_39_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C1_40_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C1_41_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C1_42_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C1_43_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C1_44_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C1_45_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C1_46_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C1_47_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C1_48_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C1_49_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C1_50_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C1_51_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C1_52_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C1_53_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C1_54_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C1_55_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C1_56_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C1_57_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C1_58_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C1_59_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C1_60_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C1_61_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C1_62_load : IN STD_LOGIC_VECTOR (31 downto 0);
    local_C1_63_load : IN STD_LOGIC_VECTOR (31 downto 0);
    p_mid2 : IN STD_LOGIC_VECTOR (9 downto 0);
    v1933_address1 : OUT STD_LOGIC_VECTOR (18 downto 0);
    v1933_ce1 : OUT STD_LOGIC;
    v1933_we1 : OUT STD_LOGIC;
    v1933_d1 : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of allo_DDitBlock_systolic_Q_Pipeline_l_store_C_tile_sj1_l_si1 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv7_40 : STD_LOGIC_VECTOR (6 downto 0) := "1000000";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal icmp_ln3648_fu_643_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal zext_ln3652_fu_1086_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal si1_fu_200 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal add_ln3649_fu_1091_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_si1_load : STD_LOGIC_VECTOR (3 downto 0);
    signal sj1_fu_204 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal select_ln3648_1_fu_681_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_sig_allocacmp_sj1_load : STD_LOGIC_VECTOR (3 downto 0);
    signal indvar_flatten13_fu_208 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    signal add_ln3648_1_fu_649_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_sig_allocacmp_indvar_flatten13_load : STD_LOGIC_VECTOR (6 downto 0);
    signal v1949_fu_1031_p19 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln3649_fu_667_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln3648_fu_661_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln3648_fu_689_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_fu_703_p17 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln3648_fu_693_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_s_fu_743_p17 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_6_fu_783_p17 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_7_fu_823_p17 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_8_fu_863_p17 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_9_fu_903_p17 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_1_fu_943_p17 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_2_fu_983_p17 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln3648_fu_673_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_fu_703_p19 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_s_fu_743_p19 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_6_fu_783_p19 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_7_fu_823_p19 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_8_fu_863_p19 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_9_fu_903_p19 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_1_fu_943_p19 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_2_fu_983_p19 : STD_LOGIC_VECTOR (31 downto 0);
    signal v1949_fu_1031_p17 : STD_LOGIC_VECTOR (31 downto 0);
    signal v1949_fu_1031_p18 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln3649_fu_1023_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln3652_fu_1072_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal empty_fu_697_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_3_fu_1078_p3 : STD_LOGIC_VECTOR (18 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal tmp_fu_703_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_fu_703_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_fu_703_p5 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_fu_703_p7 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_fu_703_p9 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_fu_703_p11 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_fu_703_p13 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_fu_703_p15 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_s_fu_743_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_s_fu_743_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_s_fu_743_p5 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_s_fu_743_p7 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_s_fu_743_p9 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_s_fu_743_p11 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_s_fu_743_p13 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_s_fu_743_p15 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_6_fu_783_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_6_fu_783_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_6_fu_783_p5 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_6_fu_783_p7 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_6_fu_783_p9 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_6_fu_783_p11 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_6_fu_783_p13 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_6_fu_783_p15 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_7_fu_823_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_7_fu_823_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_7_fu_823_p5 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_7_fu_823_p7 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_7_fu_823_p9 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_7_fu_823_p11 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_7_fu_823_p13 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_7_fu_823_p15 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_8_fu_863_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_8_fu_863_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_8_fu_863_p5 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_8_fu_863_p7 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_8_fu_863_p9 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_8_fu_863_p11 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_8_fu_863_p13 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_8_fu_863_p15 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_9_fu_903_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_9_fu_903_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_9_fu_903_p5 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_9_fu_903_p7 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_9_fu_903_p9 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_9_fu_903_p11 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_9_fu_903_p13 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_9_fu_903_p15 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_1_fu_943_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_1_fu_943_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_1_fu_943_p5 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_1_fu_943_p7 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_1_fu_943_p9 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_1_fu_943_p11 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_1_fu_943_p13 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_1_fu_943_p15 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_2_fu_983_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_2_fu_983_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_2_fu_983_p5 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_2_fu_983_p7 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_2_fu_983_p9 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_2_fu_983_p11 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_2_fu_983_p13 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_2_fu_983_p15 : STD_LOGIC_VECTOR (2 downto 0);
    signal v1949_fu_1031_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal v1949_fu_1031_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal v1949_fu_1031_p5 : STD_LOGIC_VECTOR (2 downto 0);
    signal v1949_fu_1031_p7 : STD_LOGIC_VECTOR (2 downto 0);
    signal v1949_fu_1031_p9 : STD_LOGIC_VECTOR (2 downto 0);
    signal v1949_fu_1031_p11 : STD_LOGIC_VECTOR (2 downto 0);
    signal v1949_fu_1031_p13 : STD_LOGIC_VECTOR (2 downto 0);
    signal v1949_fu_1031_p15 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component allo_DDitBlock_sparsemux_17_3_32_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (2 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (2 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (2 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (2 downto 0);
        din3_WIDTH : INTEGER;
        CASE4 : STD_LOGIC_VECTOR (2 downto 0);
        din4_WIDTH : INTEGER;
        CASE5 : STD_LOGIC_VECTOR (2 downto 0);
        din5_WIDTH : INTEGER;
        CASE6 : STD_LOGIC_VECTOR (2 downto 0);
        din6_WIDTH : INTEGER;
        CASE7 : STD_LOGIC_VECTOR (2 downto 0);
        din7_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        din2 : IN STD_LOGIC_VECTOR (31 downto 0);
        din3 : IN STD_LOGIC_VECTOR (31 downto 0);
        din4 : IN STD_LOGIC_VECTOR (31 downto 0);
        din5 : IN STD_LOGIC_VECTOR (31 downto 0);
        din6 : IN STD_LOGIC_VECTOR (31 downto 0);
        din7 : IN STD_LOGIC_VECTOR (31 downto 0);
        def : IN STD_LOGIC_VECTOR (31 downto 0);
        sel : IN STD_LOGIC_VECTOR (2 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component allo_DDitBlock_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    sparsemux_17_3_32_1_1_U1056 : component allo_DDitBlock_sparsemux_17_3_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "000",
        din0_WIDTH => 32,
        CASE1 => "001",
        din1_WIDTH => 32,
        CASE2 => "010",
        din2_WIDTH => 32,
        CASE3 => "011",
        din3_WIDTH => 32,
        CASE4 => "100",
        din4_WIDTH => 32,
        CASE5 => "101",
        din5_WIDTH => 32,
        CASE6 => "110",
        din6_WIDTH => 32,
        CASE7 => "111",
        din7_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 3,
        dout_WIDTH => 32)
    port map (
        din0 => local_C1_load,
        din1 => local_C1_1_load,
        din2 => local_C1_2_load,
        din3 => local_C1_3_load,
        din4 => local_C1_4_load,
        din5 => local_C1_5_load,
        din6 => local_C1_6_load,
        din7 => local_C1_7_load,
        def => tmp_fu_703_p17,
        sel => trunc_ln3648_fu_693_p1,
        dout => tmp_fu_703_p19);

    sparsemux_17_3_32_1_1_U1057 : component allo_DDitBlock_sparsemux_17_3_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "000",
        din0_WIDTH => 32,
        CASE1 => "001",
        din1_WIDTH => 32,
        CASE2 => "010",
        din2_WIDTH => 32,
        CASE3 => "011",
        din3_WIDTH => 32,
        CASE4 => "100",
        din4_WIDTH => 32,
        CASE5 => "101",
        din5_WIDTH => 32,
        CASE6 => "110",
        din6_WIDTH => 32,
        CASE7 => "111",
        din7_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 3,
        dout_WIDTH => 32)
    port map (
        din0 => local_C1_8_load,
        din1 => local_C1_9_load,
        din2 => local_C1_10_load,
        din3 => local_C1_11_load,
        din4 => local_C1_12_load,
        din5 => local_C1_13_load,
        din6 => local_C1_14_load,
        din7 => local_C1_15_load,
        def => tmp_s_fu_743_p17,
        sel => trunc_ln3648_fu_693_p1,
        dout => tmp_s_fu_743_p19);

    sparsemux_17_3_32_1_1_U1058 : component allo_DDitBlock_sparsemux_17_3_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "000",
        din0_WIDTH => 32,
        CASE1 => "001",
        din1_WIDTH => 32,
        CASE2 => "010",
        din2_WIDTH => 32,
        CASE3 => "011",
        din3_WIDTH => 32,
        CASE4 => "100",
        din4_WIDTH => 32,
        CASE5 => "101",
        din5_WIDTH => 32,
        CASE6 => "110",
        din6_WIDTH => 32,
        CASE7 => "111",
        din7_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 3,
        dout_WIDTH => 32)
    port map (
        din0 => local_C1_16_load,
        din1 => local_C1_17_load,
        din2 => local_C1_18_load,
        din3 => local_C1_19_load,
        din4 => local_C1_20_load,
        din5 => local_C1_21_load,
        din6 => local_C1_22_load,
        din7 => local_C1_23_load,
        def => tmp_6_fu_783_p17,
        sel => trunc_ln3648_fu_693_p1,
        dout => tmp_6_fu_783_p19);

    sparsemux_17_3_32_1_1_U1059 : component allo_DDitBlock_sparsemux_17_3_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "000",
        din0_WIDTH => 32,
        CASE1 => "001",
        din1_WIDTH => 32,
        CASE2 => "010",
        din2_WIDTH => 32,
        CASE3 => "011",
        din3_WIDTH => 32,
        CASE4 => "100",
        din4_WIDTH => 32,
        CASE5 => "101",
        din5_WIDTH => 32,
        CASE6 => "110",
        din6_WIDTH => 32,
        CASE7 => "111",
        din7_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 3,
        dout_WIDTH => 32)
    port map (
        din0 => local_C1_24_load,
        din1 => local_C1_25_load,
        din2 => local_C1_26_load,
        din3 => local_C1_27_load,
        din4 => local_C1_28_load,
        din5 => local_C1_29_load,
        din6 => local_C1_30_load,
        din7 => local_C1_31_load,
        def => tmp_7_fu_823_p17,
        sel => trunc_ln3648_fu_693_p1,
        dout => tmp_7_fu_823_p19);

    sparsemux_17_3_32_1_1_U1060 : component allo_DDitBlock_sparsemux_17_3_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "000",
        din0_WIDTH => 32,
        CASE1 => "001",
        din1_WIDTH => 32,
        CASE2 => "010",
        din2_WIDTH => 32,
        CASE3 => "011",
        din3_WIDTH => 32,
        CASE4 => "100",
        din4_WIDTH => 32,
        CASE5 => "101",
        din5_WIDTH => 32,
        CASE6 => "110",
        din6_WIDTH => 32,
        CASE7 => "111",
        din7_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 3,
        dout_WIDTH => 32)
    port map (
        din0 => local_C1_32_load,
        din1 => local_C1_33_load,
        din2 => local_C1_34_load,
        din3 => local_C1_35_load,
        din4 => local_C1_36_load,
        din5 => local_C1_37_load,
        din6 => local_C1_38_load,
        din7 => local_C1_39_load,
        def => tmp_8_fu_863_p17,
        sel => trunc_ln3648_fu_693_p1,
        dout => tmp_8_fu_863_p19);

    sparsemux_17_3_32_1_1_U1061 : component allo_DDitBlock_sparsemux_17_3_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "000",
        din0_WIDTH => 32,
        CASE1 => "001",
        din1_WIDTH => 32,
        CASE2 => "010",
        din2_WIDTH => 32,
        CASE3 => "011",
        din3_WIDTH => 32,
        CASE4 => "100",
        din4_WIDTH => 32,
        CASE5 => "101",
        din5_WIDTH => 32,
        CASE6 => "110",
        din6_WIDTH => 32,
        CASE7 => "111",
        din7_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 3,
        dout_WIDTH => 32)
    port map (
        din0 => local_C1_40_load,
        din1 => local_C1_41_load,
        din2 => local_C1_42_load,
        din3 => local_C1_43_load,
        din4 => local_C1_44_load,
        din5 => local_C1_45_load,
        din6 => local_C1_46_load,
        din7 => local_C1_47_load,
        def => tmp_9_fu_903_p17,
        sel => trunc_ln3648_fu_693_p1,
        dout => tmp_9_fu_903_p19);

    sparsemux_17_3_32_1_1_U1062 : component allo_DDitBlock_sparsemux_17_3_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "000",
        din0_WIDTH => 32,
        CASE1 => "001",
        din1_WIDTH => 32,
        CASE2 => "010",
        din2_WIDTH => 32,
        CASE3 => "011",
        din3_WIDTH => 32,
        CASE4 => "100",
        din4_WIDTH => 32,
        CASE5 => "101",
        din5_WIDTH => 32,
        CASE6 => "110",
        din6_WIDTH => 32,
        CASE7 => "111",
        din7_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 3,
        dout_WIDTH => 32)
    port map (
        din0 => local_C1_48_load,
        din1 => local_C1_49_load,
        din2 => local_C1_50_load,
        din3 => local_C1_51_load,
        din4 => local_C1_52_load,
        din5 => local_C1_53_load,
        din6 => local_C1_54_load,
        din7 => local_C1_55_load,
        def => tmp_1_fu_943_p17,
        sel => trunc_ln3648_fu_693_p1,
        dout => tmp_1_fu_943_p19);

    sparsemux_17_3_32_1_1_U1063 : component allo_DDitBlock_sparsemux_17_3_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "000",
        din0_WIDTH => 32,
        CASE1 => "001",
        din1_WIDTH => 32,
        CASE2 => "010",
        din2_WIDTH => 32,
        CASE3 => "011",
        din3_WIDTH => 32,
        CASE4 => "100",
        din4_WIDTH => 32,
        CASE5 => "101",
        din5_WIDTH => 32,
        CASE6 => "110",
        din6_WIDTH => 32,
        CASE7 => "111",
        din7_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 3,
        dout_WIDTH => 32)
    port map (
        din0 => local_C1_56_load,
        din1 => local_C1_57_load,
        din2 => local_C1_58_load,
        din3 => local_C1_59_load,
        din4 => local_C1_60_load,
        din5 => local_C1_61_load,
        din6 => local_C1_62_load,
        din7 => local_C1_63_load,
        def => tmp_2_fu_983_p17,
        sel => trunc_ln3648_fu_693_p1,
        dout => tmp_2_fu_983_p19);

    sparsemux_17_3_32_1_1_U1064 : component allo_DDitBlock_sparsemux_17_3_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "000",
        din0_WIDTH => 32,
        CASE1 => "001",
        din1_WIDTH => 32,
        CASE2 => "010",
        din2_WIDTH => 32,
        CASE3 => "011",
        din3_WIDTH => 32,
        CASE4 => "100",
        din4_WIDTH => 32,
        CASE5 => "101",
        din5_WIDTH => 32,
        CASE6 => "110",
        din6_WIDTH => 32,
        CASE7 => "111",
        din7_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 3,
        dout_WIDTH => 32)
    port map (
        din0 => tmp_fu_703_p19,
        din1 => tmp_s_fu_743_p19,
        din2 => tmp_6_fu_783_p19,
        din3 => tmp_7_fu_823_p19,
        din4 => tmp_8_fu_863_p19,
        din5 => tmp_9_fu_903_p19,
        din6 => tmp_1_fu_943_p19,
        din7 => tmp_2_fu_983_p19,
        def => v1949_fu_1031_p17,
        sel => v1949_fu_1031_p18,
        dout => v1949_fu_1031_p19);

    flow_control_loop_pipe_sequential_init_U : component allo_DDitBlock_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    indvar_flatten13_fu_208_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                if ((icmp_ln3648_fu_643_p2 = ap_const_lv1_0)) then 
                    indvar_flatten13_fu_208 <= add_ln3648_1_fu_649_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten13_fu_208 <= ap_const_lv7_0;
                end if;
            end if; 
        end if;
    end process;

    si1_fu_200_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                if ((icmp_ln3648_fu_643_p2 = ap_const_lv1_0)) then 
                    si1_fu_200 <= add_ln3649_fu_1091_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    si1_fu_200 <= ap_const_lv4_0;
                end if;
            end if; 
        end if;
    end process;

    sj1_fu_204_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                if ((icmp_ln3648_fu_643_p2 = ap_const_lv1_0)) then 
                    sj1_fu_204 <= select_ln3648_1_fu_681_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    sj1_fu_204 <= ap_const_lv4_0;
                end if;
            end if; 
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln3648_1_fu_649_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten13_load) + unsigned(ap_const_lv7_1));
    add_ln3648_fu_661_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_sj1_load) + unsigned(ap_const_lv4_1));
    add_ln3649_fu_1091_p2 <= std_logic_vector(unsigned(select_ln3648_fu_673_p3) + unsigned(ap_const_lv4_1));
    add_ln3652_fu_1072_p2 <= std_logic_vector(unsigned(p_mid2) + unsigned(zext_ln3649_fu_1023_p1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1_pp0_stage0_iter0)
    begin
        if ((ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(ap_start_int)
    begin
                ap_block_state1_pp0_stage0_iter0 <= (ap_start_int = ap_const_logic_0);
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln3648_fu_643_p2)
    begin
        if (((icmp_ln3648_fu_643_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_state1, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten13_load_assign_proc : process(ap_CS_fsm_state1, ap_loop_init, indvar_flatten13_fu_208)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_indvar_flatten13_load <= ap_const_lv7_0;
        else 
            ap_sig_allocacmp_indvar_flatten13_load <= indvar_flatten13_fu_208;
        end if; 
    end process;


    ap_sig_allocacmp_si1_load_assign_proc : process(ap_CS_fsm_state1, si1_fu_200, ap_loop_init)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_si1_load <= ap_const_lv4_0;
        else 
            ap_sig_allocacmp_si1_load <= si1_fu_200;
        end if; 
    end process;


    ap_sig_allocacmp_sj1_load_assign_proc : process(ap_CS_fsm_state1, ap_loop_init, sj1_fu_204)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_sj1_load <= ap_const_lv4_0;
        else 
            ap_sig_allocacmp_sj1_load <= sj1_fu_204;
        end if; 
    end process;

    empty_fu_697_p2 <= std_logic_vector(unsigned(tmp_22) + unsigned(zext_ln3648_fu_689_p1));
    icmp_ln3648_fu_643_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten13_load = ap_const_lv7_40) else "0";
    icmp_ln3649_fu_667_p2 <= "1" when (ap_sig_allocacmp_si1_load = ap_const_lv4_8) else "0";
    select_ln3648_1_fu_681_p3 <= 
        add_ln3648_fu_661_p2 when (icmp_ln3649_fu_667_p2(0) = '1') else 
        ap_sig_allocacmp_sj1_load;
    select_ln3648_fu_673_p3 <= 
        ap_const_lv4_0 when (icmp_ln3649_fu_667_p2(0) = '1') else 
        ap_sig_allocacmp_si1_load;
    tmp_1_fu_943_p17 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    tmp_2_fu_983_p17 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    tmp_3_fu_1078_p3 <= (add_ln3652_fu_1072_p2 & empty_fu_697_p2);
    tmp_6_fu_783_p17 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    tmp_7_fu_823_p17 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    tmp_8_fu_863_p17 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    tmp_9_fu_903_p17 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    tmp_fu_703_p17 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    tmp_s_fu_743_p17 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    trunc_ln3648_fu_693_p1 <= select_ln3648_1_fu_681_p3(3 - 1 downto 0);
    v1933_address1 <= zext_ln3652_fu_1086_p1(19 - 1 downto 0);

    v1933_ce1_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            v1933_ce1 <= ap_const_logic_1;
        else 
            v1933_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    v1933_d1 <= v1949_fu_1031_p19;

    v1933_we1_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln3648_fu_643_p2)
    begin
        if (((icmp_ln3648_fu_643_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            v1933_we1 <= ap_const_logic_1;
        else 
            v1933_we1 <= ap_const_logic_0;
        end if; 
    end process;

    v1949_fu_1031_p17 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    v1949_fu_1031_p18 <= select_ln3648_fu_673_p3(3 - 1 downto 0);
    zext_ln3648_fu_689_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln3648_1_fu_681_p3),9));
    zext_ln3649_fu_1023_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln3648_fu_673_p3),10));
    zext_ln3652_fu_1086_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_3_fu_1078_p3),64));
end behav;
